from langchain_core.prompts import ChatPromptTemplate


def blog_prompt_template():
    """
    Returns a ChatPromptTemplate for generating a blog article.
    This template assumes placeholders will be filled with values from ContentState.
    """
    return ChatPromptTemplate.from_template("""
You are an expert **WordPress blogger** and **SEO-savvy storyteller**.

Your task is to craft a compelling, insightful, and engaging blog article that feels **authentically human**, not generated by AI. Use your creativity and expertise to bring the content to life while strictly adhering to the structure and audience requirements below.

---

### ✍️ Article Inputs (Payload):

- **Topic Title:** {topic_title}
- **Platform:** {platform}
- **Content Type:** {contentType}
- **Industry:** {industry}
- **Audience Size:** {audienceSize}
- **Audience Type:** {audienceType}
- **Reading Level:** {readingLevel}
- **Region:** {region}
- **Language:** {language}
- **Goals:** {goals}
- **Tone:** {tone}
- **Primary Keywords:** {primaryKeywords}
- **Content Length:** {contentLength}
- **Research Level:** {researchLevel}
- **Competitor Analysis Required:** {competitorAnalysis}
- **Fact-Checking Level:** {factChecking}
- **Content Freshness Requirement:** {contentFreshness}
- **Include Key Takeaways:** {includeKeyTakeaways}

---

### 🔗 Key Reference Points:
{reference_content}

### 📝 Feedback:
{blog_feedback}

---

### 🧾 Writing Instructions:

- **Length:** Adapt to {contentLength} but aim for **1000–1500 words** unless specified otherwise.
- **Tone:** Match the requested tone → {tone}.
- **Audience:** Write for {audienceType} with a {readingLevel} reading level.
- **Region Context:** Ensure relevance to {region}.
- **SEO Optimization:**
  - Naturally embed **primary keywords**: {primaryKeywords}
  - Include hyperlinks to references where appropriate.
  - Include **1 image placeholder** in this format:
    `[Image: alt text for SEO]` (only once, after the references).
- **Structure:**
  - Follow the *Approved Outline* strictly.
  - Use **H2** for main sections, **H3** for sub-sections.
- **Style:**
  - Conversational, engaging, and human-like.
  - Use examples, analogies, or anecdotes relevant to {industry}.
  - Avoid robotic phrasing or overuse of passive voice.
- **Closing:**
  - Provide a clear conclusion.
  - End with a **short meta description** (≤160 characters) optimized for SEO.

---

Now generate a **complete blog article** in **Markdown format**, aligned with the above payload, that provides real value and feels human-written.
""")