import asyncio
import os
import time
from dotenv import load_dotenv

from src.web.shopify_bridge import ShopifyAppBridge

# Load environment variables from .env
load_dotenv()

async def test_publish():
    print("Testing Shopify publish endpoint...")

    shared_secret = os.getenv("SHOPIFY_BRIDGE_SHARED_SECRET")
    base_url = os.getenv("SHOPIFY_BRIDGE_BASE_URL", "https://gas-heated-oxygen-moral.trycloudflare.com")

    print(f"Base URL: {base_url}")

    bridge = ShopifyAppBridge(
        shared_secret=shared_secret,
        base_url=base_url
    )

    # Timestamp suffix avoids "Handle has already been taken" on re-runs
    ts = int(time.time())
    handle = f"rext-test-post-{ts}"

    try:
        result = await bridge.publish_blog_post(
            store_url="thebotlab.myshopify.com",
            title=f"Rext AI Test Post {ts}",
            body="<p>This is a test post from Rext. Generated by the publish test script.</p>",
            published=True,
            tags=["AI", "Rext"],
            handle=handle,
            feature_image_url=None,
            content_id=f"test-content-{ts}",
            workspace_id="test-workspace-123"
        )
        print("✅ Blog post published successfully!")
        print(f"  Article ID  : {result.get('article_id')}")
        print(f"  Article URL : {result.get('article_url')}")
        print(f"  Title       : {result.get('title')}")
        print(f"  Published at: {result.get('published_at')}")
        print(f"  Raw response: {result.get('raw_response')}")
    except Exception as e:
        print("❌ Publishing failed — blog post was NOT created in Shopify:")
        print(str(e))

if __name__ == "__main__":
    asyncio.run(test_publish())
