from sqlalchemy import Column, String, Text, Integer, Float, DateTime, Boolean, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, ARRAY, JSONB
from sqlalchemy.orm import relationship
from src.api.database.base import Base
from src.api.models.base import SerializableMixin
from datetime import datetime
import uuid


class Content(Base, SerializableMixin):
    """Main content table - stores generated content"""
    __tablename__ = "content"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, unique=True, nullable=False)
    workspace_id = Column(UUID(as_uuid=True), ForeignKey("workspace.id", ondelete="CASCADE"), nullable=False, index=True)
    created_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=False, index=True)

    # Core content fields (generated by flow)
    title = Column(Text, nullable=False, comment="SEO-optimized article title")
    slug = Column(Text, unique=True, nullable=False, index=True, comment="URL-friendly slug")
    meta_title = Column(Text, nullable=True, comment="Meta title for SEO (50-60 chars)")
    meta_description = Column(Text, nullable=True, comment="Meta description for SEO (150-160 chars)")
    introduction = Column(Text, nullable=True, comment="Opening paragraph (150-300 words)")
    body_markdown = Column(Text, nullable=True, comment="Main article body in Markdown")
    body_html = Column(Text, nullable=True, comment="Main article body in HTML (converted from markdown)")
    
    # SEO fields
    focus_keyphrase = Column(Text, nullable=True, comment="Primary focus keyphrase")
    keyphrase_density = Column(Float, nullable=True, comment="Keyphrase density percentage")
    tags = Column(ARRAY(Text), nullable=True, comment="Article tags")
    
    # Status and metadata
    status = Column(Text, nullable=True, default="draft", comment="draft, ready, published")
    content_language = Column(Text, nullable=True, default="English")

    # LangGraph workflow tracking
    langgraph_thread_id = Column(UUID(as_uuid=True), nullable=True, index=True,
                                  comment="LangGraph workflow thread ID for content generation tracking")

    # Flow-generated structured data (JSONB)
    secondary_keywords = Column(ARRAY(Text), nullable=True, comment="Secondary keywords")
    images_data = Column(JSONB, nullable=True, comment="Image alt text suggestions and placements")
    links_data = Column(JSONB, nullable=True, comment="Internal and outbound links")
    schema_markup = Column(JSONB, nullable=True, comment="Structured data/schema markup")
    seo_score = Column(JSONB, nullable=True, comment="On-page SEO scoring details")
    readability_score = Column(JSONB, nullable=True, comment="Readability analysis")
    
    # WordPress publishing fields
    wordpress_post_id = Column(Integer, nullable=True, comment="WordPress post ID after publishing")
    wordpress_url = Column(Text, nullable=True, comment="Published WordPress post URL")
    wordpress_published_at = Column(DateTime(timezone=True), nullable=True, comment="When published to WordPress")

    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), nullable=True, default=datetime.utcnow, onupdate=datetime.utcnow)
    deleted_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    workspace = relationship("WorkspaceModel", back_populates="content_items")
    created_by = relationship("Users", foreign_keys=[created_by_user_id])

    # Note: All content data is now stored in this table
    # Removed separate tables for progress, seo_data, reviews, versions to simplify

    # to_dict() inherited from SerializableMixin
    def to_dict(self):
        return {
            "id": self.id,
            "workspace_id": self.workspace_id,
            "created_by_user_id": self.created_by_user_id,
            "assigned_to_user_id": self.assigned_to_user_id,
            "author_id": self.author_id,
            "featured_image_id": self.featured_image_id,
            "title": self.title,
            "slug": self.slug,
            "body_markdown": self.body_markdown,
            "body_html": self.body_html,
            "content_format": self.content_format,
            "status": self.status,
            "content_language": self.content_language,
            "langgraph_thread_id": self.langgraph_thread_id,
            "metadata_json": self.metadata_json,
            "tracking_json": self.tracking_json,
            "ai_config_json": self.ai_config_json,
            "structure_json": self.structure_json,
            "research_config_json": self.research_config_json,
            "published_at": self.published_at,
            "submitted_for_review_at": self.submitted_for_review_at,
            "reviewed_at": self.reviewed_at,
            "reviewed_by_user_id": self.reviewed_by_user_id,
            "review_notes": self.review_notes,
            "wordpress_post_id": self.wordpress_post_id,
            "wordpress_url": self.wordpress_url,
            "wordpress_published_at": self.wordpress_published_at,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "deleted_at": self.deleted_at,
        }
