import logging
from typing import List, Optional

from pydantic import BaseModel, Field, model_validator

from src.flow.model.structure.outline import Fact

logger = logging.getLogger(__name__)


class ImageAltText(BaseModel):
    """Represents an SEO-optimized alt text and optional URL for an image."""

    url: Optional[str] = Field(
        default=None,
        description="The direct URL of the image, if generated by a tool (e.g., DALL-E).",
    )
    alt_text: str = Field(
        description="SEO-optimized alt text containing the keyphrase or synonyms for the image."
    )
    context: str = Field(
        description="Description of what this image shows (e.g., 'screenshot of dashboard', 'infographic showing statistics', 'diagram of process')."
    )
    placement: str = Field(
        description="Where in the article this image should appear (e.g., 'introduction', 'section-2', 'conclusion')."
    )
    status: Optional[str] = Field(
        default=None,
        description=(
            "Set to 'pending_manual_upload' when image generation was disabled and "
            "this entry is a manual-upload placeholder awaiting a real image from "
            "the user, rather than an AI-generated or hallucinated one."
        ),
    )
    placeholder_id: Optional[str] = Field(
        default=None,
        description=(
            "Matches the id encoded in the body_markdown placeholder marker "
            "(rext-placeholder:<id>) when status is 'pending_manual_upload'."
        ),
    )


class Link(BaseModel):
    """Represents an internal or outbound link."""

    url: str = Field(description="Link URL.")
    anchor_text: str = Field(description="Anchor text for the link.")
    link_type: str = Field(description="Type of link: 'internal' or 'outbound'.")
    placement: str = Field(
        description="Where in the article this link should appear (e.g., 'introduction', 'section-1', 'conclusion')."
    )
    rel: Optional[str] = Field(
        default=None,
        description=(
            "Link relationship attribute. SEO rule: internal links should be DoFollow "
            "(leave this null/omit it). Outbound links should be 'nofollow' unless there "
            "is a specific reason to keep it followed (e.g. a verified partner/citation "
            "link), in which case use 'sponsored' or another explicit override."
        ),
    )


class CTABlock(BaseModel):
    """The primary call-to-action, when the outline declares one for this content type."""

    text: str = Field(description="Exact CTA text/phrase as it appears in the content.")
    url: Optional[str] = Field(
        default=None, description="CTA destination URL, if it links anywhere."
    )
    placement: str = Field(
        default="body",
        description="Where in the article this CTA appears (e.g., 'hero', 'body', 'conclusion').",
    )


class SchemaMarkup(BaseModel):
    """Represents structured data/schema markup for the article."""

    schema_type: str = Field(
        default="Article", description="Schema.org type (e.g., 'Article', 'HowTo', 'FAQPage')."
    )
    schema_data: str = Field(
        description="Complete JSON-LD schema markup as a JSON string (to be parsed as JSON)."
    )


class GeneratedContent(BaseModel):
    """Validated output of the content generation step with comprehensive SEO requirements."""

    # Core Content
    title: str = Field(description="Final SEO-optimized article title starting with the keyphrase.")
    slug: str = Field(
        description="URL-friendly slug containing the keyphrase (e.g., 'best-seo-tools-2026')."
    )

    # SEO Meta Tags
    meta_title: str = Field(
        description="Meta title: identical to the user-selected title, verbatim (50-59 chars)."
    )
    meta_description: str = Field(
        description="Meta description containing the keyphrase (120-140 chars, hard maximum 140)."
    )
    tags: List[str] = Field(description="List of tags for the article.")
    category: Optional[str] = Field(
        default=None,
        description="One concise topical WordPress category name for this article.",
    )

    # Keywords
    focus_keyphrase: str = Field(
        description="The primary focus keyphrase for this article (2-4 words recommended)."
    )
    keyphrase_density: float = Field(
        ge=0.0,
        le=10.0,
        description="Keyphrase density percentage (ideal target: 0.5%-2.5%, acceptable: 0.1%-5.0%).",
    )
    secondary_keywords: List[str] = Field(
        default=[], description="Secondary keywords for the article."
    )

    # Introduction
    introduction: str = Field(
        description="Opening paragraph(s) that introduce the topic and contain the keyphrase naturally (target: 150-300 words in Markdown).",
        min_length=50,
        max_length=5000,
    )

    # Main Content
    body_markdown: str = Field(
        description="Complete article body written in Markdown format (excluding introduction), following the approved outline. Must include subheadings with keyphrase variants. CRITICAL: Every URL in the internal_links field MUST appear as an inline hyperlink [anchor text](url) woven into the most topically relevant sentence in this field.",
        min_length=200,
        max_length=60000,
    )

    # Image Alt Text Suggestions
    images: List[ImageAltText] = Field(
        default=[],
        description="List of SEO-optimized alt text suggestions for images that should be added to the content. Include at least 1 suggestion when possible.",
    )

    # Links
    internal_links: List[Link] = Field(
        default=[],
        description="MANDATORY: populate with every internal link from the prompt's INTERNAL LINKS block. Every URL here MUST also appear as an inline hyperlink inside body_markdown.",
    )
    outbound_links: List[Link] = Field(
        default=[],
        description="Outbound links to authoritative external sources. Include at least 1 when possible.",
    )

    # Schema Markup
    schema_markup: SchemaMarkup = Field(
        description="Structured data/schema markup for the article."
    )

    facts: List[Fact] = Field(
        default_factory=list,
        description="List of key verifiable facts or statistics with source URLs included in the content.",
    )

    @model_validator(mode="after")
    def enforce_internal_links_in_body(self) -> "GeneratedContent":
        """Hard fallback: any internal link URL not found in body_markdown gets appended."""
        if not self.body_markdown or not self.internal_links:
            return self
        body = self.body_markdown
        missing = [lnk for lnk in self.internal_links if lnk.url and lnk.url not in body]
        if missing:
            appended = "\n\n" + "\n".join(
                f"[{lnk.anchor_text or lnk.url}]({lnk.url})" for lnk in missing
            )
            self.body_markdown = body + appended
        return self
