"""align_notification_and_admin_invitation_indexes

Revision ID: 2a18e6a49dbf
Revises: 263449deebd4
Create Date: 2026-02-24 23:08:41.929596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a18e6a49dbf'
down_revision: Union[str, Sequence[str], None] = '263449deebd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('category_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('notification_preferences', 'ws_invite_received')
    op.drop_column('notification_preferences', 'billing_subscription_expiring')
    op.drop_column('notification_preferences', 'gen_failed')
    op.drop_column('notification_preferences', 'email_product_updates')
    op.drop_column('notification_preferences', 'ws_invite_accepted')
    op.drop_column('notification_preferences', 'billing_subscription_cancelled')
    op.drop_column('notification_preferences', 'email_billing_updates')
    op.drop_column('notification_preferences', 'in_app_content_updates')
    op.drop_column('notification_preferences', 'billing_payment_failed')
    op.drop_column('notification_preferences', 'billing_trial_ending')
    op.drop_column('notification_preferences', 'in_app_team_activity')
    op.drop_column('notification_preferences', 'in_app_security_alerts')
    op.drop_column('notification_preferences', 'gen_started')
    op.drop_column('notification_preferences', 'email_team_activity')
    op.drop_column('notification_preferences', 'kb_processing_failed')
    op.drop_column('notification_preferences', 'kb_processing_completed')
    op.drop_column('notification_preferences', 'email_comments')
    op.drop_column('notification_preferences', 'in_app_mentions')
    op.drop_column('notification_preferences', 'gen_completed')
    op.drop_column('notification_preferences', 'email_security_alerts')
    op.drop_column('notification_preferences', 'email_content_updates')
    op.drop_column('notification_preferences', 'in_app_billing_updates')
    op.drop_column('notification_preferences', 'in_app_product_updates')
    op.drop_column('notification_preferences', 'in_app_comments')
    op.drop_column('notification_preferences', 'billing_usage_limit_exceeded')
    op.drop_column('notification_preferences', 'billing_usage_limit_warning')
    op.drop_column('notification_preferences', 'ws_member_removed')
    op.drop_column('notification_preferences', 'gen_published')
    op.drop_column('notification_preferences', 'billing_payment_success')
    op.drop_column('notification_preferences', 'email_mentions')
    op.drop_column('notification_preferences', 'ws_role_changed')
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_index(op.f('idx_user_created'), table_name='notifications')
    op.drop_index(op.f('idx_user_type_created'), table_name='notifications')
    op.drop_index(op.f('idx_workspace_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('idx_user_read_deleted'), table_name='notifications')
    op.create_index('idx_user_read_deleted', 'notifications', ['user_id', 'is_read', 'deleted_at'], unique=False)
    op.create_index('idx_notif_user_active_created', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_notif_user_category_created', 'notifications', ['user_id', 'category', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_notif_user_type_created', 'notifications', ['user_id', 'type', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_notif_user_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL AND is_read = false'))
    op.create_index('idx_notif_user_workspace_created', 'notifications', ['user_id', 'workspace_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('notifications', 'is_deleted')
    op.drop_constraint(op.f('uq_admin_invitation_email'), 'platform_admin_invitations', type_='unique')
    op.create_index('uq_admin_invitation_email_pending', 'platform_admin_invitations', ['email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_user_invitations_email_status', 'user_invitations', ['email', 'status'], unique=False)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_index('ix_user_invitations_email_status', table_name='user_invitations')
    op.drop_index('uq_admin_invitation_email_pending', table_name='platform_admin_invitations', postgresql_where=sa.text("status = 'pending'"))
    op.create_unique_constraint(op.f('uq_admin_invitation_email'), 'platform_admin_invitations', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('notifications', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index('idx_notif_user_workspace_created', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_notif_user_unread', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL AND is_read = false'))
    op.drop_index('idx_notif_user_type_created', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_notif_user_category_created', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_notif_user_active_created', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_user_read_deleted', table_name='notifications')
    op.create_index(op.f('idx_user_read_deleted'), 'notifications', ['user_id', 'is_read', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_workspace_created'), 'notifications', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_user_type_created'), 'notifications', ['user_id', 'type', 'created_at'], unique=False)
    op.create_index(op.f('idx_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.add_column('notification_preferences', sa.Column('ws_role_changed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_mentions', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('billing_payment_success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('gen_published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('ws_member_removed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('billing_usage_limit_warning', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('billing_usage_limit_exceeded', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_comments', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_product_updates', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_billing_updates', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_content_updates', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_security_alerts', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('gen_completed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_mentions', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_comments', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('kb_processing_completed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('kb_processing_failed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_team_activity', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('gen_started', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_security_alerts', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_team_activity', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('billing_trial_ending', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('billing_payment_failed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_content_updates', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_billing_updates', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('billing_subscription_cancelled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('ws_invite_accepted', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_product_updates', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('gen_failed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('billing_subscription_expiring', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('ws_invite_received', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('notification_preferences', 'category_preferences')
    # ### end Alembic commands ###
