"""restore_content_seo_and_integrations

Revision ID: 2d09d2bad33e
Revises: 2dd447802ac2
Create Date: 2026-01-16 22:38:19.849568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d09d2bad33e'
down_revision: Union[str, Sequence[str], None] = '2dd447802ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_versions_content_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_connected_sites_integration_type'), table_name='connected_sites')
    op.drop_index(op.f('ix_connected_sites_workspace_id'), table_name='connected_sites')
    op.drop_table('connected_sites')
    op.drop_index(op.f('ix_workspace_integrations_integration_type'), table_name='workspace_integrations')
    op.drop_index(op.f('ix_workspace_integrations_workspace_id'), table_name='workspace_integrations')
    op.drop_table('workspace_integrations')
    op.create_table('integrations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('workspace_id', sa.UUID(), nullable=False),
        sa.Column('integration_type', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('site_url', sa.String(length=500), nullable=True, comment='WordPress site URL'),
        sa.Column('api_endpoint', sa.String(length=500), nullable=True, comment='Rext-AI Plugin Base Endpoint'),
        sa.Column('username', sa.String(length=255), nullable=True, comment='WordPress username'),
        sa.Column('app_password', sa.Text(), nullable=True, comment='WordPress application password'),
        sa.Column('api_key', sa.Text(), nullable=True, comment='WordPress Rext-AI API Key (Bearer Token)'),
        sa.Column('shop_domain', sa.String(length=500), nullable=True, comment='Shopify shop domain'),
        sa.Column('access_token', sa.Text(), nullable=True, comment='Shopify access token'),
        sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional integration configuration and settings'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('now()')),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_integrations_integration_type'), 'integrations', ['integration_type'], unique=False)
    op.create_unique_constraint(None, 'brand_voice', ['id'])
    op.alter_column('content', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='SEO-optimized article title',
               existing_nullable=False)
    op.alter_column('content', 'slug',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='URL-friendly slug',
               existing_nullable=False)
    op.alter_column('content', 'introduction',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Opening paragraph (150-300 words)',
               existing_nullable=True)
    op.alter_column('content', 'body_markdown',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Main article body in Markdown',
               existing_nullable=True)
    op.alter_column('content', 'body_html',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Main article body in HTML (converted from markdown)',
               existing_nullable=True)
    op.alter_column('content', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='draft, ready, published',
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('content', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='Tags (common to content)',
               existing_comment='Article tags',
               existing_nullable=True)
    op.alter_column('content', 'langgraph_thread_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='LangGraph workflow thread ID for content generation tracking',
               existing_nullable=True)
    op.alter_column('content', 'images_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Inline images data',
               existing_comment='Image alt text suggestions and placements',
               existing_nullable=True)
    op.alter_column('content', 'wordpress_post_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='WordPress post ID after publishing',
               existing_nullable=True)
    op.alter_column('content', 'wordpress_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Published WordPress post URL',
               existing_nullable=True)
    op.alter_column('content', 'wordpress_published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When published to WordPress',
               existing_nullable=True)
    op.alter_column('content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('content_slug_key'), 'content', type_='unique')
    op.drop_index(op.f('ix_content_created_at'), table_name='content')
    op.drop_index(op.f('ix_content_status'), table_name='content')
    op.drop_index(op.f('ix_content_workspace_created_at'), table_name='content')
    op.drop_index(op.f('ix_content_workspace_status'), table_name='content')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=True)
    op.create_unique_constraint(None, 'content', ['id'])
    op.drop_column('content', 'readability_score')
    op.drop_column('content', 'keyphrase_density')
    op.drop_column('content', 'meta_title')
    op.drop_column('content', 'secondary_keywords')
    op.drop_column('content', 'seo_score')
    op.drop_column('content', 'focus_keyphrase')
    op.drop_column('content', 'meta_description')
    op.alter_column('content_media', 'content_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Content that uses this media',
               existing_nullable=False)
    op.alter_column('content_media', 'media_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Media file used in content',
               existing_nullable=False)
    op.alter_column('content_media', 'usage_type',
               existing_type=sa.VARCHAR(length=50),
               comment='How media is used: inline, gallery, attachment, embed, etc.',
               existing_comment='How media is used: inline, gallery, attachment, etc.',
               existing_nullable=True)
    op.alter_column('content_media', 'position',
               existing_type=sa.INTEGER(),
               comment='Position/order in content (for sorting)',
               existing_comment='Position in content (for ordering)',
               existing_nullable=True)
    op.drop_index(op.f('ix_content_media_media_id_content_id'), table_name='content_media')
    op.drop_constraint(op.f('uq_content_media'), 'content_media', type_='unique')
    op.add_column('content_seo_data', sa.Column('meta_title', sa.Text(), nullable=True, comment='Meta title (50-60 chars)'))
    op.add_column('content_seo_data', sa.Column('meta_description', sa.Text(), nullable=True, comment='Meta description (150-160 chars)'))
    op.add_column('content_seo_data', sa.Column('focus_keyphrase', sa.Text(), nullable=True, comment='Primary focus keyphrase'))
    op.add_column('content_seo_data', sa.Column('keyphrase_density', sa.Float(), nullable=True, comment='Keyphrase density percentage'))
    op.add_column('content_seo_data', sa.Column('secondary_keywords', postgresql.ARRAY(sa.Text()), nullable=True, comment='Secondary keywords'))
    op.add_column('content_seo_data', sa.Column('search_intent', postgresql.ARRAY(sa.Text()), nullable=True, comment='informational, navigational, etc.'))
    op.add_column('content_seo_data', sa.Column('seo_score', sa.Float(), nullable=True))
    op.add_column('content_seo_data', sa.Column('readability_score', sa.Float(), nullable=True))
    op.add_column('content_seo_data', sa.Column('seo_details', sa.Text(), nullable=True, comment='Detailed SEO analysis/feedback'))
    op.alter_column('content_seo_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('content_seo_data', 'content_readability_score')
    op.drop_column('content_seo_data', 'content_meta_description')
    op.drop_column('content_seo_data', 'content_primary_keywords')
    op.drop_column('content_seo_data', 'content_seo_score')
    op.drop_column('content_seo_data', 'content_search_intent')
    op.drop_column('content_seo_data', 'content_secondary_keywords')
    op.alter_column('discount_usage', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Amount saved (in currency or percentage)',
               existing_nullable=True)
    op.alter_column('discount_usage', 'discount_amount_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Type: 'percent' or 'fixed'",
               existing_nullable=True)
    op.alter_column('discount_usage', 'order_id',
               existing_type=sa.VARCHAR(length=255),
               comment='LemonSqueezy order ID',
               existing_nullable=True)
    op.alter_column('discount_usage', 'lemonsqueezy_discount_id',
               existing_type=sa.VARCHAR(length=255),
               comment='LemonSqueezy discount ID',
               existing_nullable=True)
    op.alter_column('discount_usage', 'usage_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional discount information from LemonSqueezy',
               existing_nullable=True)
    op.drop_index(op.f('idx_discount_usage_applied_at'), table_name='discount_usage')
    op.drop_index(op.f('idx_discount_usage_code'), table_name='discount_usage')
    op.drop_index(op.f('idx_discount_usage_subscription_id'), table_name='discount_usage')
    op.drop_index(op.f('idx_discount_usage_user_id'), table_name='discount_usage')
    op.create_index(op.f('ix_discount_usage_applied_at'), 'discount_usage', ['applied_at'], unique=False)
    op.create_index(op.f('ix_discount_usage_discount_code'), 'discount_usage', ['discount_code'], unique=False)
    op.create_index(op.f('ix_discount_usage_subscription_id'), 'discount_usage', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_discount_usage_user_id'), 'discount_usage', ['user_id'], unique=False)
    op.drop_index(op.f('idx_email_events_log'), table_name='email_events')
    op.drop_index(op.f('idx_email_events_provider_message'), table_name='email_events')
    op.drop_index(op.f('idx_email_events_received_at'), table_name='email_events')
    op.drop_index(op.f('idx_email_events_type'), table_name='email_events')
    op.create_index(op.f('ix_email_events_email_log_id'), 'email_events', ['email_log_id'], unique=False)
    op.create_index(op.f('ix_email_events_event_type'), 'email_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_events_provider_message_id'), 'email_events', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_events_received_at'), 'email_events', ['received_at'], unique=False)
    op.drop_index(op.f('idx_email_logs_created_at'), table_name='email_logs')
    op.drop_index(op.f('idx_email_logs_provider_message_id'), table_name='email_logs')
    op.drop_index(op.f('idx_email_logs_status'), table_name='email_logs')
    op.drop_index(op.f('idx_email_logs_to_email'), table_name='email_logs')
    op.drop_index(op.f('idx_email_logs_user'), table_name='email_logs')
    op.drop_index(op.f('idx_email_logs_workspace'), table_name='email_logs')
    op.create_index(op.f('ix_email_logs_created_at'), 'email_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_logs_provider_message_id'), 'email_logs', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_logs_status'), 'email_logs', ['status'], unique=False)
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_logs_workspace_id'), 'email_logs', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_email_preferences_unsubscribe_token'), table_name='email_preferences')
    op.drop_index(op.f('ix_email_preferences_user_id'), table_name='email_preferences')
    # op.alter_column('email_templates', 'workspace_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    op.alter_column('email_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('email_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('idx_email_templates_type'), table_name='email_templates')
    op.drop_index(op.f('idx_email_templates_workspace_id'), table_name='email_templates')
    op.drop_index(op.f('idx_email_templates_workspace_type_active'), table_name='email_templates')
    op.create_unique_constraint(None, 'email_templates', ['id'])
    op.drop_constraint(op.f('email_templates_created_by_user_id_fkey'), 'email_templates', type_='foreignkey')
    op.drop_constraint(op.f('email_templates_workspace_id_fkey'), 'email_templates', type_='foreignkey')
    op.create_foreign_key(None, 'email_templates', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'email_templates', 'workspace', ['workspace_id'], ['id'])
    op.alter_column('error_logs', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # op.create_unique_constraint(None, 'integrations', ['id'])
    op.alter_column('knowledge_base', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type: default, custom',
               existing_nullable=False)
    op.drop_index(op.f('ix_knowledge_base_type'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_workspace_id'), table_name='knowledge_base')
    op.create_unique_constraint(None, 'knowledge_base', ['id'])
    op.drop_index(op.f('ix_knowledge_files_hash'), table_name='knowledge_files')
    op.drop_index(op.f('ix_knowledge_files_knowledge_base_id'), table_name='knowledge_files')
    op.create_index(op.f('ix_knowledge_files_file_hash'), 'knowledge_files', ['file_hash'], unique=False)
    op.create_unique_constraint(None, 'knowledge_files', ['id'])
    op.drop_index(op.f('idx_license_activations_active'), table_name='license_activations')
    op.drop_index(op.f('idx_license_activations_instance_id'), table_name='license_activations')
    op.drop_index(op.f('idx_license_activations_license_id'), table_name='license_activations')
    op.drop_index(op.f('idx_license_activations_license_instance'), table_name='license_activations')
    op.create_index(op.f('ix_license_activations_instance_id'), 'license_activations', ['instance_id'], unique=False)
    op.create_index(op.f('ix_license_activations_is_active'), 'license_activations', ['is_active'], unique=False)
    op.create_index(op.f('ix_license_activations_license_id'), 'license_activations', ['license_id'], unique=False)
    op.create_unique_constraint(None, 'license_activations', ['id'])
    op.create_unique_constraint(None, 'licenses', ['id'])
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_index(op.f('ix_media_search'), table_name='media', postgresql_using='gin')
    op.drop_column('notification_preferences', 'email_comments')
    op.drop_column('notification_preferences', 'in_app_workspace_invites')
    op.drop_column('notification_preferences', 'email_billing_updates')
    op.drop_column('notification_preferences', 'in_app_comments')
    op.drop_column('notification_preferences', 'email_content_updates')
    op.drop_column('notification_preferences', 'email_mentions')
    op.drop_column('notification_preferences', 'in_app_security_alerts')
    op.drop_column('notification_preferences', 'email_product_updates')
    op.drop_column('notification_preferences', 'in_app_billing_updates')
    op.drop_column('notification_preferences', 'email_security_alerts')
    op.drop_column('notification_preferences', 'in_app_content_updates')
    op.drop_column('notification_preferences', 'email_team_activity')
    op.drop_column('notification_preferences', 'in_app_product_updates')
    op.drop_column('notification_preferences', 'email_digest_frequency')
    op.drop_column('notification_preferences', 'in_app_mentions')
    op.drop_column('notification_preferences', 'in_app_team_activity')
    op.drop_column('notification_preferences', 'email_workspace_invites')
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.create_unique_constraint(None, 'oauth_accounts', ['id'])
    op.drop_index(op.f('ix_payment_methods_is_default'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_provider_customer_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.create_unique_constraint(None, 'payment_methods', ['id'])
    op.drop_constraint(op.f('uq_permissions_name'), 'permissions', type_='unique')
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.drop_index(op.f('idx_persona_workspace_id'), table_name='persona')
    op.create_unique_constraint(None, 'persona', ['id'])
    op.drop_index(op.f('idx_admin_invitations_email_status_pending'), table_name='platform_admin_invitations', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('ix_platform_admin_invitations_expires_at'), table_name='platform_admin_invitations')
    op.drop_index(op.f('ix_platform_admin_invitations_token'), table_name='platform_admin_invitations')
    op.drop_constraint(op.f('platform_admin_invitations_invitation_token_key'), 'platform_admin_invitations', type_='unique')
    op.create_index(op.f('ix_platform_admin_invitations_invitation_token'), 'platform_admin_invitations', ['invitation_token'], unique=True)
    op.create_unique_constraint(None, 'platform_admin_invitations', ['id'])
    op.create_unique_constraint(None, 'role_permissions', ['id'])
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['id'])
    op.drop_index(op.f('ix_subscription_plans_lemonsqueezy_variant_monthly'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_lemonsqueezy_variant_yearly'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_lemonsqueezy_variant_id_monthly'), 'subscription_plans', ['lemonsqueezy_variant_id_monthly'], unique=False)
    op.create_index(op.f('ix_subscription_plans_lemonsqueezy_variant_id_yearly'), 'subscription_plans', ['lemonsqueezy_variant_id_yearly'], unique=False)
    op.drop_index(op.f('ix_text_knowledge_knowledge_base_id'), table_name='text_knowledge')
    op.create_unique_constraint(None, 'text_knowledge', ['id'])
    op.alter_column('trial_conversions', 'conversion_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional conversion data (discount code, source, etc.)',
               existing_comment='Additional conversion data',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_trial_conversions_converted_at'), table_name='trial_conversions')
    op.drop_index(op.f('idx_trial_conversions_plan_id'), table_name='trial_conversions')
    op.drop_index(op.f('idx_trial_conversions_subscription_id'), table_name='trial_conversions')
    op.drop_index(op.f('idx_trial_conversions_user_id'), table_name='trial_conversions')
    op.create_index(op.f('ix_trial_conversions_conversion_plan_id'), 'trial_conversions', ['conversion_plan_id'], unique=False)
    op.create_index(op.f('ix_trial_conversions_converted_at'), 'trial_conversions', ['converted_at'], unique=False)
    op.create_index(op.f('ix_trial_conversions_subscription_id'), 'trial_conversions', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_trial_conversions_user_id'), 'trial_conversions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'trial_conversions', ['id'])
    op.drop_index(op.f('idx_invitations_email_status_pending'), table_name='user_invitations', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_invitations_expiry_pending'), table_name='user_invitations', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_invitations_invited_by'), table_name='user_invitations')
    op.drop_index(op.f('idx_invitations_workspace_pending'), table_name='user_invitations', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_invitations_workspace_status_created'), table_name='user_invitations')
    op.create_unique_constraint(None, 'user_invitations', ['id'])
    op.drop_constraint(op.f('user_onboarding_user_id_key'), 'user_onboarding', type_='unique')
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=True)
    op.create_unique_constraint(None, 'user_onboarding', ['id'])
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.drop_index(op.f('idx_user_roles_user_workspace'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_user_workspace'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_workspace_role'), table_name='user_roles')
    op.create_unique_constraint(None, 'user_roles', ['id'])
    op.create_index('idx_user_sessions_jti', 'user_sessions', ['jti'], unique=False)
    op.create_index('idx_user_sessions_last_activity', 'user_sessions', ['last_activity_at'], unique=False)
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'webhook_events', ['id'])
    op.drop_index(op.f('ix_website_knowledge_base_id'), table_name='website')
    op.create_unique_constraint(None, 'website', ['id'])
    op.alter_column('workspace', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='IANA timezone identifier (e.g., America/New_York, UTC)',
               existing_nullable=True)
    op.drop_index(op.f('ix_workspace_deleted_at'), table_name='workspace')
    op.drop_constraint(op.f('uq_workspace_slug'), 'workspace', type_='unique')
    op.drop_constraint(op.f('workspace_slug_key'), 'workspace', type_='unique')
    op.create_unique_constraint(None, 'workspace', ['id'])
    op.drop_constraint(op.f('fk_workspace_deleted_by_users'), 'workspace', type_='foreignkey')
    op.create_foreign_key(None, 'workspace', 'users', ['deleted_by'], ['id'])
    op.drop_index(op.f('idx_workspace_members_user_active'), table_name='workspace_members', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('idx_workspace_members_user_workspace'), table_name='workspace_members')
    op.drop_index(op.f('idx_workspace_members_workspace_status'), table_name='workspace_members')
    op.create_unique_constraint(None, 'workspace_members', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='unique')
    op.create_index(op.f('idx_workspace_members_workspace_status'), 'workspace_members', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('idx_workspace_members_user_workspace'), 'workspace_members', ['user_id', 'workspace_id'], unique=False)
    op.create_index(op.f('idx_workspace_members_user_active'), 'workspace_members', ['user_id'], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspace_deleted_by_users'), 'workspace', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'workspace', type_='unique')
    op.create_unique_constraint(op.f('workspace_slug_key'), 'workspace', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_workspace_slug'), 'workspace', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_workspace_deleted_at'), 'workspace', ['deleted_at'], unique=False)
    op.alter_column('workspace', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment='IANA timezone identifier (e.g., America/New_York, UTC)',
               existing_nullable=True)
    op.drop_constraint(None, 'website', type_='unique')
    op.create_index(op.f('ix_website_knowledge_base_id'), 'website', ['knowledge_base_id'], unique=False)
    op.drop_constraint(None, 'webhook_events', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.drop_index('idx_user_sessions_last_activity', table_name='user_sessions')
    op.drop_index('idx_user_sessions_jti', table_name='user_sessions')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.create_index(op.f('ix_user_roles_workspace_role'), 'user_roles', ['workspace_id', 'role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_workspace'), 'user_roles', ['user_id', 'workspace_id'], unique=False)
    op.create_index(op.f('idx_user_roles_user_workspace'), 'user_roles', ['user_id', 'workspace_id'], unique=False)
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_constraint(None, 'user_onboarding', type_='unique')
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_onboarding_user_id_key'), 'user_onboarding', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_invitations', type_='unique')
    op.create_index(op.f('idx_invitations_workspace_status_created'), 'user_invitations', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('idx_invitations_workspace_pending'), 'user_invitations', ['workspace_id'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('idx_invitations_invited_by'), 'user_invitations', ['invited_by_user_id'], unique=False)
    op.create_index(op.f('idx_invitations_expiry_pending'), 'user_invitations', ['expires_at', 'status'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('idx_invitations_email_status_pending'), 'user_invitations', ['email', 'status'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_constraint(None, 'trial_conversions', type_='unique')
    op.drop_index(op.f('ix_trial_conversions_user_id'), table_name='trial_conversions')
    op.drop_index(op.f('ix_trial_conversions_subscription_id'), table_name='trial_conversions')
    op.drop_index(op.f('ix_trial_conversions_converted_at'), table_name='trial_conversions')
    op.drop_index(op.f('ix_trial_conversions_conversion_plan_id'), table_name='trial_conversions')
    op.create_index(op.f('idx_trial_conversions_user_id'), 'trial_conversions', ['user_id'], unique=False)
    op.create_index(op.f('idx_trial_conversions_subscription_id'), 'trial_conversions', ['subscription_id'], unique=False)
    op.create_index(op.f('idx_trial_conversions_plan_id'), 'trial_conversions', ['conversion_plan_id'], unique=False)
    op.create_index(op.f('idx_trial_conversions_converted_at'), 'trial_conversions', ['converted_at'], unique=False)
    op.alter_column('trial_conversions', 'conversion_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional conversion data',
               existing_comment='Additional conversion data (discount code, source, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'text_knowledge', type_='unique')
    op.create_index(op.f('ix_text_knowledge_knowledge_base_id'), 'text_knowledge', ['knowledge_base_id'], unique=False)
    op.drop_index(op.f('ix_subscription_plans_lemonsqueezy_variant_id_yearly'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_lemonsqueezy_variant_id_monthly'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_lemonsqueezy_variant_yearly'), 'subscription_plans', ['lemonsqueezy_variant_id_yearly'], unique=False)
    op.create_index(op.f('ix_subscription_plans_lemonsqueezy_variant_monthly'), 'subscription_plans', ['lemonsqueezy_variant_id_monthly'], unique=False)
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'role_permissions', type_='unique')
    op.drop_constraint(None, 'platform_admin_invitations', type_='unique')
    op.drop_index(op.f('ix_platform_admin_invitations_invitation_token'), table_name='platform_admin_invitations')
    op.create_unique_constraint(op.f('platform_admin_invitations_invitation_token_key'), 'platform_admin_invitations', ['invitation_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_platform_admin_invitations_token'), 'platform_admin_invitations', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_platform_admin_invitations_expires_at'), 'platform_admin_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('idx_admin_invitations_email_status_pending'), 'platform_admin_invitations', ['email', 'status'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_constraint(None, 'persona', type_='unique')
    op.create_index(op.f('idx_persona_workspace_id'), 'persona', ['workspace_id'], unique=False)
    op.drop_constraint(None, 'permissions', type_='unique')
    op.create_unique_constraint(op.f('uq_permissions_name'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'payment_methods', type_='unique')
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_provider_customer_id'), 'payment_methods', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_is_default'), 'payment_methods', ['user_id', 'is_default'], unique=False)
    op.drop_constraint(None, 'oauth_accounts', type_='unique')
    op.drop_constraint(None, 'notifications', type_='unique')
    op.add_column('notification_preferences', sa.Column('email_workspace_invites', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_team_activity', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_mentions', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_digest_frequency', sa.VARCHAR(length=20), server_default=sa.text("'daily'::character varying"), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_product_updates', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_team_activity', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_content_updates', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_security_alerts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_billing_updates', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_product_updates', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_security_alerts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_mentions', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_content_updates', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_comments', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_billing_updates', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('in_app_workspace_invites', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('email_comments', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_media_search'), 'media', [sa.literal_column("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.drop_constraint(None, 'licenses', type_='unique')
    op.drop_constraint(None, 'license_activations', type_='unique')
    op.drop_index(op.f('ix_license_activations_license_id'), table_name='license_activations')
    op.drop_index(op.f('ix_license_activations_is_active'), table_name='license_activations')
    op.drop_index(op.f('ix_license_activations_instance_id'), table_name='license_activations')
    op.create_index(op.f('idx_license_activations_license_instance'), 'license_activations', ['license_id', 'instance_id'], unique=False)
    op.create_index(op.f('idx_license_activations_license_id'), 'license_activations', ['license_id'], unique=False)
    op.create_index(op.f('idx_license_activations_instance_id'), 'license_activations', ['instance_id'], unique=False)
    op.create_index(op.f('idx_license_activations_active'), 'license_activations', ['license_id', 'is_active'], unique=False)
    op.drop_constraint(None, 'knowledge_files', type_='unique')
    op.drop_index(op.f('ix_knowledge_files_file_hash'), table_name='knowledge_files')
    op.create_index(op.f('ix_knowledge_files_knowledge_base_id'), 'knowledge_files', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_files_hash'), 'knowledge_files', ['file_hash'], unique=False)
    op.drop_constraint(None, 'knowledge_base', type_='unique')
    op.create_index(op.f('ix_knowledge_base_workspace_id'), 'knowledge_base', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_type'), 'knowledge_base', ['type'], unique=False)
    op.alter_column('knowledge_base', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type: default, custom',
               existing_nullable=False)
    op.drop_constraint(None, 'integrations', type_='unique')
    op.alter_column('error_logs', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.create_foreign_key(op.f('email_templates_workspace_id_fkey'), 'email_templates', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('email_templates_created_by_user_id_fkey'), 'email_templates', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'email_templates', type_='unique')
    op.create_index(op.f('idx_email_templates_workspace_type_active'), 'email_templates', ['workspace_id', 'template_type', 'is_active'], unique=False)
    op.create_index(op.f('idx_email_templates_workspace_id'), 'email_templates', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_email_templates_type'), 'email_templates', ['template_type'], unique=False)
    op.alter_column('email_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('email_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('email_templates', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_email_preferences_user_id'), 'email_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_preferences_unsubscribe_token'), 'email_preferences', ['unsubscribe_token'], unique=False)
    op.drop_index(op.f('ix_email_logs_workspace_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_status'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_provider_message_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_created_at'), table_name='email_logs')
    op.create_index(op.f('idx_email_logs_workspace'), 'email_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_email_logs_user'), 'email_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    op.create_index(op.f('idx_email_logs_status'), 'email_logs', ['status'], unique=False)
    op.create_index(op.f('idx_email_logs_provider_message_id'), 'email_logs', ['provider_message_id'], unique=False)
    op.create_index(op.f('idx_email_logs_created_at'), 'email_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_email_events_received_at'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_provider_message_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_type'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_email_log_id'), table_name='email_events')
    op.create_index(op.f('idx_email_events_type'), 'email_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_email_events_received_at'), 'email_events', ['received_at'], unique=False)
    op.create_index(op.f('idx_email_events_provider_message'), 'email_events', ['provider_message_id'], unique=False)
    op.create_index(op.f('idx_email_events_log'), 'email_events', ['email_log_id'], unique=False)
    op.drop_index(op.f('ix_discount_usage_user_id'), table_name='discount_usage')
    op.drop_index(op.f('ix_discount_usage_subscription_id'), table_name='discount_usage')
    op.drop_index(op.f('ix_discount_usage_discount_code'), table_name='discount_usage')
    op.drop_index(op.f('ix_discount_usage_applied_at'), table_name='discount_usage')
    op.create_index(op.f('idx_discount_usage_user_id'), 'discount_usage', ['user_id'], unique=False)
    op.create_index(op.f('idx_discount_usage_subscription_id'), 'discount_usage', ['subscription_id'], unique=False)
    op.create_index(op.f('idx_discount_usage_code'), 'discount_usage', ['discount_code'], unique=False)
    op.create_index(op.f('idx_discount_usage_applied_at'), 'discount_usage', ['applied_at'], unique=False)
    op.alter_column('discount_usage', 'usage_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional discount information from LemonSqueezy',
               existing_nullable=True)
    op.alter_column('discount_usage', 'lemonsqueezy_discount_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='LemonSqueezy discount ID',
               existing_nullable=True)
    op.alter_column('discount_usage', 'order_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='LemonSqueezy order ID',
               existing_nullable=True)
    op.alter_column('discount_usage', 'discount_amount_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Type: 'percent' or 'fixed'",
               existing_nullable=True)
    op.alter_column('discount_usage', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Amount saved (in currency or percentage)',
               existing_nullable=True)
    op.add_column('content_seo_data', sa.Column('content_secondary_keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('content_seo_data', sa.Column('content_search_intent', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('content_seo_data', sa.Column('content_seo_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('content_seo_data', sa.Column('content_primary_keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('content_seo_data', sa.Column('content_meta_description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('content_seo_data', sa.Column('content_readability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('content_seo_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('content_seo_data', 'seo_details')
    op.drop_column('content_seo_data', 'readability_score')
    op.drop_column('content_seo_data', 'seo_score')
    op.drop_column('content_seo_data', 'search_intent')
    op.drop_column('content_seo_data', 'secondary_keywords')
    op.drop_column('content_seo_data', 'keyphrase_density')
    op.drop_column('content_seo_data', 'focus_keyphrase')
    op.drop_column('content_seo_data', 'meta_description')
    op.drop_column('content_seo_data', 'meta_title')
    op.create_unique_constraint(op.f('uq_content_media'), 'content_media', ['content_id', 'media_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_content_media_media_id_content_id'), 'content_media', ['media_id', 'content_id'], unique=False)
    op.alter_column('content_media', 'position',
               existing_type=sa.INTEGER(),
               comment='Position in content (for ordering)',
               existing_comment='Position/order in content (for sorting)',
               existing_nullable=True)
    op.alter_column('content_media', 'usage_type',
               existing_type=sa.VARCHAR(length=50),
               comment='How media is used: inline, gallery, attachment, etc.',
               existing_comment='How media is used: inline, gallery, attachment, embed, etc.',
               existing_nullable=True)
    op.alter_column('content_media', 'media_id',
               existing_type=sa.UUID(),
               comment='Media file used in content',
               existing_nullable=False)
    op.alter_column('content_media', 'content_id',
               existing_type=sa.UUID(),
               comment='Content that uses this media',
               existing_nullable=False)
    op.add_column('content', sa.Column('meta_description', sa.TEXT(), autoincrement=False, nullable=True, comment='Meta description for SEO (150-160 chars)'))
    op.add_column('content', sa.Column('focus_keyphrase', sa.TEXT(), autoincrement=False, nullable=True, comment='Primary focus keyphrase'))
    op.add_column('content', sa.Column('seo_score', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='On-page SEO scoring details'))
    op.add_column('content', sa.Column('secondary_keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True, comment='Secondary keywords'))
    op.add_column('content', sa.Column('meta_title', sa.TEXT(), autoincrement=False, nullable=True, comment='Meta title for SEO (50-60 chars)'))
    op.add_column('content', sa.Column('keyphrase_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Keyphrase density percentage'))
    op.add_column('content', sa.Column('readability_score', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Readability analysis'))
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=False)
    op.create_index(op.f('ix_content_workspace_status'), 'content', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_content_workspace_created_at'), 'content', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_content_status'), 'content', ['status'], unique=False)
    op.create_index(op.f('ix_content_created_at'), 'content', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('content_slug_key'), 'content', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('content', 'wordpress_published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When published to WordPress',
               existing_nullable=True)
    op.alter_column('content', 'wordpress_url',
               existing_type=sa.TEXT(),
               comment='Published WordPress post URL',
               existing_nullable=True)
    op.alter_column('content', 'wordpress_post_id',
               existing_type=sa.INTEGER(),
               comment='WordPress post ID after publishing',
               existing_nullable=True)
    op.alter_column('content', 'images_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Image alt text suggestions and placements',
               existing_comment='Inline images data',
               existing_nullable=True)
    op.alter_column('content', 'langgraph_thread_id',
               existing_type=sa.UUID(),
               comment='LangGraph workflow thread ID for content generation tracking',
               existing_nullable=True)
    op.alter_column('content', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='Article tags',
               existing_comment='Tags (common to content)',
               existing_nullable=True)
    op.alter_column('content', 'status',
               existing_type=sa.TEXT(),
               comment='draft, ready, published',
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('content', 'body_html',
               existing_type=sa.TEXT(),
               comment='Main article body in HTML (converted from markdown)',
               existing_nullable=True)
    op.alter_column('content', 'body_markdown',
               existing_type=sa.TEXT(),
               comment='Main article body in Markdown',
               existing_nullable=True)
    op.alter_column('content', 'introduction',
               existing_type=sa.TEXT(),
               comment='Opening paragraph (150-300 words)',
               existing_nullable=True)
    op.alter_column('content', 'slug',
               existing_type=sa.TEXT(),
               comment='URL-friendly slug',
               existing_nullable=False)
    op.alter_column('content', 'title',
               existing_type=sa.TEXT(),
               comment='SEO-optimized article title',
               existing_nullable=False)
    op.drop_constraint(None, 'brand_voice', type_='unique')
    op.create_table('workspace_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('site_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shop_domain', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('workspace_integrations_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_integrations_pkey'))
    )
    op.create_index(op.f('ix_workspace_integrations_workspace_id'), 'workspace_integrations', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_integrations_integration_type'), 'workspace_integrations', ['integration_type'], unique=False)
    op.create_table('connected_sites',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('site_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='WordPress site URL'),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='WordPress username'),
    sa.Column('app_password', sa.TEXT(), autoincrement=False, nullable=True, comment='WordPress application password'),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional integration configuration and settings'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.TEXT(), autoincrement=False, nullable=True, comment='WordPress Rext-AI API Key (Bearer Token)'),
    sa.Column('api_endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Rext-AI Plugin Base Endpoint'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('connected_sites_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('connected_sites_pkey'))
    )
    op.create_index(op.f('ix_connected_sites_workspace_id'), 'connected_sites', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_connected_sites_integration_type'), 'connected_sites', ['integration_type'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('content_versions_content_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_versions_pkey'))
    )
    op.create_index(op.f('ix_content_versions_content_id'), 'content_versions', ['content_id'], unique=False)
    # ### end Alembic commands ###
