"""remove_content_tracking_tables

Revision ID: 2dd447802ac2
Revises: c7e0547bf440
Create Date: 2026-01-16 19:11:46.709307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dd447802ac2'
down_revision: Union[str, Sequence[str], None] = 'c7e0547bf440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS content_tracking CASCADE")
    op.execute("DROP TABLE IF EXISTS content_research_config CASCADE")
    op.execute("DROP TABLE IF EXISTS content_structure CASCADE")
    op.execute("DROP TABLE IF EXISTS content_progress CASCADE")
    op.execute("DROP TABLE IF EXISTS content_ai_config CASCADE")
    op.execute("DROP TABLE IF EXISTS content_review CASCADE")
    op.execute("DROP TABLE IF EXISTS content_metadata CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrade is empty because we don't want to restore these deprecated tables
    pass
    # ### end Alembic commands ###
