"""remove_unused_cdn_url_column_from_media

Revision ID: 36d18c584625
Revises: 1f6d82da1298
Create Date: 2026-02-20 09:42:13.359196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.utils.encryption

# revision identifiers, used by Alembic.
revision: str = '36d18c584625'
down_revision: Union[str, Sequence[str], None] = '1f6d82da1298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('content', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_constraint(op.f('content_title_key'), 'content', type_='unique')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=False)
    op.create_unique_constraint('uq_content_workspace_slug', 'content', ['workspace_id', 'slug'])
    op.create_unique_constraint('uq_content_workspace_title', 'content', ['workspace_id', 'title'])
    op.create_unique_constraint(None, 'discount_usage', ['id'])
    op.add_column('email_logs', sa.Column('html_content', sa.Text(), nullable=True))
    op.alter_column('integrations', 'app_password',
               existing_type=sa.TEXT(),
               type_=src.utils.encryption.EncryptedText(),
               comment='WordPress application password (encrypted)',
               existing_comment='WordPress application password',
               existing_nullable=True)
    op.alter_column('integrations', 'api_key',
               existing_type=sa.TEXT(),
               type_=src.utils.encryption.EncryptedText(),
               comment='WordPress Rext-AI API Key (encrypted)',
               existing_comment='WordPress Rext-AI API Key (Bearer Token)',
               existing_nullable=True)
    op.alter_column('integrations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.create_index('ix_knowledge_base_workspace_name', 'knowledge_base', ['workspace_id', 'name'], unique=False)
    op.create_index('ix_knowledge_base_workspace_type', 'knowledge_base', ['workspace_id', 'type'], unique=False)
    op.create_index('ix_knowledge_files_workspace_hash', 'knowledge_files', ['workspace_id', 'file_hash'], unique=False)
    op.create_index('ix_knowledge_files_workspace_kb', 'knowledge_files', ['workspace_id', 'knowledge_base_id'], unique=False)
    op.create_index('idx_license_activations_active', 'license_activations', ['license_id', 'is_active'], unique=False)
    op.create_index('idx_license_activations_license_instance', 'license_activations', ['license_id', 'instance_id'], unique=False)
    op.alter_column('media', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='Whether file is publicly accessible — derived from access_level',
               existing_comment='Whether file is publicly accessible',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('media', 'cdn_url')
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of notification',
               existing_comment='Type of notification: workspace, billing, content, knowledge, system, etc.',
               existing_nullable=False)
    op.alter_column('notifications', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Specific notification category',
               existing_comment='Specific category: ws_invite_received, billing_payment_failed, kb_processing_completed, etc.',
               existing_nullable=True)
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Priority level: low, normal, high, urgent',
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Status: new, success, warning, error, info',
               existing_nullable=False)
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional data in JSON format (e.g., workspace_id, content_id, etc.)',
               existing_nullable=True)
    op.alter_column('notifications', 'action_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL to navigate to when notification is clicked',
               existing_nullable=True)
    op.alter_column('notifications', 'action_label',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Label for the action button (e.g., 'View Workspace', 'View Invoice')",
               existing_nullable=True)
    op.alter_column('notifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this notification should expire and be auto-archived',
               existing_nullable=True)
    op.drop_index(op.f('idx_user_read_deleted'), table_name='notifications')
    op.create_index('idx_user_read_deleted', 'notifications', ['user_id', 'is_read', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint(None, 'permissions', ['name'])
    op.create_index('ix_text_knowledge_workspace_kb', 'text_knowledge', ['workspace_id', 'knowledge_base_id'], unique=False)
    op.drop_index(op.f('ix_user_invitations_invited_by_user_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_role_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_invitations_workspace_id'), table_name='user_invitations')
    op.drop_index(op.f('ix_user_roles_assigned_by_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_workspace_id'), table_name='user_roles')
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_workspace_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_assigned_by_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['assigned_by_user_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'workspace', ['workspace_id'], ['id'])
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.create_index('ix_website_workspace_kb', 'website', ['workspace_id', 'knowledge_base_id'], unique=False)
    op.create_index('ix_website_workspace_url', 'website', ['workspace_id', 'url'], unique=False)
    op.alter_column('workspace', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('workspace_members', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('workspace_members', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_workspace_members_invitation_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_invitation_id'), 'workspace_members', ['invitation_id'], unique=False)
    op.alter_column('workspace_members', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workspace_members', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('workspace', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_index('ix_website_workspace_url', table_name='website')
    op.drop_index('ix_website_workspace_kb', table_name='website')
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_assigned_by_user_id_fkey'), 'user_roles', 'users', ['assigned_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_roles_workspace_id_fkey'), 'user_roles', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_roles_workspace_id'), 'user_roles', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_assigned_by_user_id'), 'user_roles', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_user_invitations_workspace_id'), 'user_invitations', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_user_invitations_role_id'), 'user_invitations', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_invitations_invited_by_user_id'), 'user_invitations', ['invited_by_user_id'], unique=False)
    op.drop_index('ix_text_knowledge_workspace_kb', table_name='text_knowledge')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index('idx_user_read_deleted', table_name='notifications')
    op.create_index(op.f('idx_user_read_deleted'), 'notifications', ['user_id', 'is_read', 'deleted_at'], unique=False)
    op.alter_column('notifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this notification should expire and be auto-archived',
               existing_nullable=True)
    op.alter_column('notifications', 'action_label',
               existing_type=sa.VARCHAR(length=100),
               comment="Label for the action button (e.g., 'View Workspace', 'View Invoice')",
               existing_nullable=True)
    op.alter_column('notifications', 'action_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL to navigate to when notification is clicked',
               existing_nullable=True)
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional data in JSON format (e.g., workspace_id, content_id, etc.)',
               existing_nullable=True)
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status: new, success, warning, error, info',
               existing_nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='Priority level: low, normal, high, urgent',
               existing_nullable=False)
    op.alter_column('notifications', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Specific category: ws_invite_received, billing_payment_failed, kb_processing_completed, etc.',
               existing_comment='Specific notification category',
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of notification: workspace, billing, content, knowledge, system, etc.',
               existing_comment='Type of notification',
               existing_nullable=False)
    op.drop_column('notifications', 'is_deleted')
    op.add_column('media', sa.Column('cdn_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='CDN URL if available'))
    op.alter_column('media', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='Whether file is publicly accessible',
               existing_comment='Whether file is publicly accessible — derived from access_level',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_license_activations_license_instance', table_name='license_activations')
    op.drop_index('idx_license_activations_active', table_name='license_activations')
    op.drop_index('ix_knowledge_files_workspace_kb', table_name='knowledge_files')
    op.drop_index('ix_knowledge_files_workspace_hash', table_name='knowledge_files')
    op.drop_index('ix_knowledge_base_workspace_type', table_name='knowledge_base')
    op.drop_index('ix_knowledge_base_workspace_name', table_name='knowledge_base')
    op.alter_column('integrations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('integrations', 'api_key',
               existing_type=src.utils.encryption.EncryptedText(),
               type_=sa.TEXT(),
               comment='WordPress Rext-AI API Key (Bearer Token)',
               existing_comment='WordPress Rext-AI API Key (encrypted)',
               existing_nullable=True)
    op.alter_column('integrations', 'app_password',
               existing_type=src.utils.encryption.EncryptedText(),
               type_=sa.TEXT(),
               comment='WordPress application password',
               existing_comment='WordPress application password (encrypted)',
               existing_nullable=True)
    op.drop_column('email_logs', 'html_content')
    op.drop_constraint(None, 'discount_usage', type_='unique')
    op.drop_constraint('uq_content_workspace_title', 'content', type_='unique')
    op.drop_constraint('uq_content_workspace_slug', 'content', type_='unique')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=True)
    op.create_unique_constraint(op.f('content_title_key'), 'content', ['title'], postgresql_nulls_not_distinct=False)
    op.alter_column('content', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('content', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
