"""rename content_strategy to content_pillar in brand voice

Revision ID: 3c187ecaf50f
Revises: 263449deebd4
Create Date: 2026-02-26 11:41:57.721660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c187ecaf50f'
down_revision: Union[str, Sequence[str], None] = '263449deebd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_voice', sa.Column('content_pillar', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('brand_voice', 'content_strategy')
    """op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('idx_user_read_deleted'), table_name='notifications')
    op.create_index('idx_user_read_deleted', 'notifications', ['user_id', 'is_read', 'deleted_at'], unique=False)
    op.drop_column('notifications', 'is_deleted')
    op.create_index('ix_user_invitations_email_status', 'user_invitations', ['email', 'status'], unique=False)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)"""
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_index('ix_user_invitations_email_status', table_name='user_invitations')
    op.add_column('notifications', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index('idx_user_read_deleted', table_name='notifications')
    op.create_index(op.f('idx_user_read_deleted'), 'notifications', ['user_id', 'is_read', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)"""
    op.add_column('brand_voice', sa.Column('content_strategy', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('brand_voice', 'content_pillar')
    # ### end Alembic commands ###
