"""rename first and last name to full_name

Revision ID: 4ad3dc4bea19
Revises: 2d09d2bad33e
Create Date: 2026-01-29 14:06:04.474664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad3dc4bea19'
down_revision: Union[str, Sequence[str], None] = '2d09d2bad33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    if 'impersonation_sessions' not in tables:
        op.create_table('impersonation_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('invalidated_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_impersonation_sessions_session_id'), 'impersonation_sessions', ['session_id'], unique=True)
    if 'full_name' not in [c['name'] for c in inspector.get_columns('audit_logs')]:
        op.add_column('audit_logs', sa.Column('full_name', sa.String(length=200), nullable=True))
    
    if 'username' in [c['name'] for c in inspector.get_columns('audit_logs')]:
        op.drop_column('audit_logs', 'username')
    if not any(set(c['column_names']) == {'title'} for c in inspector.get_unique_constraints('content')):
        op.create_unique_constraint(None, 'content', ['title'])
    
    if not any(set(c['column_names']) == {'id'} for c in inspector.get_unique_constraints('integrations')):
        op.create_unique_constraint(None, 'integrations', ['id'])
    
    integration_columns = [c['name'] for c in inspector.get_columns('integrations')]
    if 'access_token' in integration_columns:
        op.drop_column('integrations', 'access_token')
    if 'shop_domain' in integration_columns:
        op.drop_column('integrations', 'shop_domain')

    if 'full_name' not in [c['name'] for c in inspector.get_columns('users')]:
        op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=True))
    
    # Check if constraint exists before dropping
    constraints = inspector.get_unique_constraints('users')
    if any(c['name'] == 'users_username_key' for c in constraints):
        op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    
    user_columns = [c['name'] for c in inspector.get_columns('users')]
    if 'first_name' in user_columns:
        op.drop_column('users', 'first_name')
    if 'username' in user_columns:
        op.drop_column('users', 'username')
    if 'last_name' in user_columns:
        op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'full_name')
    op.add_column('integrations', sa.Column('shop_domain', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Shopify shop domain'))
    op.add_column('integrations', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True, comment='Shopify access token'))
    op.drop_constraint(None, 'integrations', type_='unique')
    op.drop_constraint(None, 'content', type_='unique')
    op.add_column('audit_logs', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('audit_logs', 'full_name')
    op.drop_index(op.f('ix_impersonation_sessions_session_id'), table_name='impersonation_sessions')
    op.drop_table('impersonation_sessions')
    # ### end Alembic commands ###
