"""add_composite_indexes_knowledge_models

Revision ID: 5b86d5d6d4dd
Revises: c9893663dd80
Create Date: 2026-02-13 12:14:04.065710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b86d5d6d4dd'
down_revision: Union[str, Sequence[str], None] = 'c9893663dd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_base_workspace_name', 'knowledge_base', ['workspace_id', 'name'], unique=False)
    op.create_index('ix_knowledge_base_workspace_type', 'knowledge_base', ['workspace_id', 'type'], unique=False)
    op.create_index('ix_knowledge_files_workspace_hash', 'knowledge_files', ['workspace_id', 'file_hash'], unique=False)
    op.create_index('ix_knowledge_files_workspace_kb', 'knowledge_files', ['workspace_id', 'knowledge_base_id'], unique=False)
    op.create_index('ix_text_knowledge_workspace_kb', 'text_knowledge', ['workspace_id', 'knowledge_base_id'], unique=False)
    op.create_index('ix_website_workspace_kb', 'website', ['workspace_id', 'knowledge_base_id'], unique=False)
    op.create_index('ix_website_workspace_url', 'website', ['workspace_id', 'url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_website_workspace_url', table_name='website')
    op.drop_index('ix_website_workspace_kb', table_name='website')
    op.drop_index('ix_text_knowledge_workspace_kb', table_name='text_knowledge')
    op.drop_index('ix_knowledge_files_workspace_kb', table_name='knowledge_files')
    op.drop_index('ix_knowledge_files_workspace_hash', table_name='knowledge_files')
    op.drop_index('ix_knowledge_base_workspace_type', table_name='knowledge_base')
    op.drop_index('ix_knowledge_base_workspace_name', table_name='knowledge_base')
    # ### end Alembic commands ###
