"""recreate topics table

Revision ID: 628c252172f3
Revises: 5701c27278fe
Create Date: 2026-04-10 16:19:43.649897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '628c252172f3'
down_revision: Union[str, Sequence[str], None] = '5701c27278fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('generated_by_first_name', sa.String(), nullable=True),
    sa.Column('generated_by_last_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('angle', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('channel_fit', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('audience_fit', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('why_it_works', sa.String(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('suggested_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goal_alignment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_guidance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audience_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('internal_research_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_topics_workspace_id'), 'topics', ['workspace_id'], unique=False)
    op.add_column('content', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_content_topic_id'), 'content', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'content', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_index(op.f('ix_content_topic_id'), table_name='content')
    op.drop_column('content', 'topic_id')
    op.drop_index(op.f('ix_topics_workspace_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
