"""add_cancellation_reason_to_user_subscriptions

Revision ID: 6bcd0442f08e
Revises: merge_20260210
Create Date: 2026-02-12 10:24:01.486736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcd0442f08e'
down_revision: Union[str, Sequence[str], None] = 'merge_20260210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'cancellation_reason')
    # ### end Alembic commands ###
