"""add_unique_constraints_and_remove_duplicate_indexes

Revision ID: 86049af81ad3
Revises: 8a1b2c3d4e5f
Create Date: 2026-02-10 16:16:05.990132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86049af81ad3'
down_revision: Union[str, Sequence[str], None] = '8a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_content_media', 'content_media', ['content_id', 'media_id'])
    op.alter_column('customer_notes', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('customer_notes_admin_id_fkey'), 'customer_notes', type_='foreignkey')
    op.create_foreign_key(None, 'customer_notes', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('email_templates_created_by_user_id_fkey'), 'email_templates', type_='foreignkey')
    op.drop_constraint(op.f('email_templates_workspace_id_fkey'), 'email_templates', type_='foreignkey')
    op.create_foreign_key(None, 'email_templates', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'email_templates', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('error_logs_resolved_by_fkey'), 'error_logs', type_='foreignkey')
    op.drop_constraint(op.f('error_logs_user_id_fkey'), 'error_logs', type_='foreignkey')
    op.create_foreign_key(None, 'error_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'error_logs', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.create_unique_constraint(None, 'token_blacklist', ['jti'])
    op.alter_column('trial_conversions', 'conversion_plan_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Plan user converted to')
    op.alter_column('user_invitations', 'invited_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('user_invitations_role_id_fkey'), 'user_invitations', type_='foreignkey')
    op.drop_constraint(op.f('user_invitations_invited_by_user_id_fkey'), 'user_invitations', type_='foreignkey')
    op.drop_constraint(op.f('user_invitations_workspace_id_fkey'), 'user_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'user_invitations', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_invitations', 'users', ['invited_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_invitations', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint('uq_user_role_workspace', 'user_roles', ['user_id', 'role_id', 'workspace_id'])
    op.drop_constraint(op.f('user_roles_role_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_workspace_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.drop_constraint(op.f('user_roles_assigned_by_user_id_fkey'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['assigned_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_last_activity_at'), table_name='user_sessions')
    op.create_unique_constraint(None, 'user_sessions', ['jti'])
    op.drop_constraint(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('workspace_deleted_by_fkey'), 'workspace', type_='foreignkey')
    op.drop_constraint(op.f('workspace_user_id_fkey'), 'workspace', type_='foreignkey')
    op.create_foreign_key(None, 'workspace', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_user_workspace', 'workspace_members', ['user_id', 'workspace_id'])
    op.drop_constraint(op.f('workspace_members_user_id_fkey'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('workspace_members_invitation_id_fkey'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'user_invitations', ['invitation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workspace_members', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', 'workspace', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('workspace_members_invitation_id_fkey'), 'workspace_members', 'user_invitations', ['invitation_id'], ['id'])
    op.create_foreign_key(op.f('workspace_members_user_id_fkey'), 'workspace_members', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_workspace', 'workspace_members', type_='unique')
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_user_id_fkey'), 'workspace', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('workspace_deleted_by_fkey'), 'workspace', 'users', ['deleted_by'], ['id'])
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_last_activity_at'), 'user_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_assigned_by_user_id_fkey'), 'user_roles', 'users', ['assigned_by_user_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_user_id_fkey'), 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_workspace_id_fkey'), 'user_roles', 'workspace', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('user_roles_role_id_fkey'), 'user_roles', 'roles', ['role_id'], ['id'])
    op.drop_constraint('uq_user_role_workspace', 'user_roles', type_='unique')
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('user_invitations_workspace_id_fkey'), 'user_invitations', 'workspace', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('user_invitations_invited_by_user_id_fkey'), 'user_invitations', 'users', ['invited_by_user_id'], ['id'])
    op.create_foreign_key(op.f('user_invitations_role_id_fkey'), 'user_invitations', 'roles', ['role_id'], ['id'])
    op.alter_column('user_invitations', 'invited_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trial_conversions', 'conversion_plan_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Plan user converted to')
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.drop_constraint(None, 'error_logs', type_='foreignkey')
    op.drop_constraint(None, 'error_logs', type_='foreignkey')
    op.create_foreign_key(op.f('error_logs_user_id_fkey'), 'error_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('error_logs_resolved_by_fkey'), 'error_logs', 'users', ['resolved_by'], ['id'])
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.create_foreign_key(op.f('email_templates_workspace_id_fkey'), 'email_templates', 'workspace', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('email_templates_created_by_user_id_fkey'), 'email_templates', 'users', ['created_by_user_id'], ['id'])
    op.drop_constraint(None, 'customer_notes', type_='foreignkey')
    op.create_foreign_key(op.f('customer_notes_admin_id_fkey'), 'customer_notes', 'users', ['admin_id'], ['id'])
    op.alter_column('customer_notes', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('uq_content_media', 'content_media', type_='unique')
    op.alter_column('content', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
