"""record the workspace pipeline's latest run on the workspace

Revision ID: 87d0834f8a64
Revises: 28a7cf7247ad
Create Date: 2026-10-07 09:22:44.190548

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87d0834f8a64"
down_revision: Union[str, Sequence[str], None] = "28a7cf7247ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("pipeline_status", sa.String(length=20), nullable=True))
    op.add_column(
        "workspace", sa.Column("pipeline_operation_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "workspace", sa.Column("pipeline_started_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "pipeline_started_at")
    op.drop_column("workspace", "pipeline_operation_id")
    op.drop_column("workspace", "pipeline_status")
    # ### end Alembic commands ###
