"""Add notifications table

Revision ID: 986b51dfac84
Revises: 300c2952d43d
Create Date: 2025-11-28 15:42:11.509525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '986b51dfac84'
down_revision: Union[str, Sequence[str], None] = '300c2952d43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Type of notification: workspace, billing, content, knowledge, system, etc.'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Specific category: ws_invite_received, billing_payment_failed, kb_processing_completed, etc.'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='Priority level: low, normal, high, urgent'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: new, success, warning, error, info'),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional data in JSON format (e.g., workspace_id, content_id, etc.)'),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='URL to navigate to when notification is clicked'),
    sa.Column('action_label', sa.String(length=100), nullable=True, comment="Label for the action button (e.g., 'View Workspace', 'View Invoice')"),
    sa.Column('sent_via_email', sa.Boolean(), nullable=False),
    sa.Column('sent_via_sse', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('sse_sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True, comment='When this notification should expire and be auto-archived'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_read_deleted', 'notifications', ['user_id', 'is_read', 'is_deleted'], unique=False)
    op.create_index('idx_user_type_created', 'notifications', ['user_id', 'type', 'created_at'], unique=False)
    op.create_index('idx_workspace_created', 'notifications', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_is_archived'), 'notifications', ['is_archived'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_archived'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_index('idx_workspace_created', table_name='notifications')
    op.drop_index('idx_user_type_created', table_name='notifications')
    op.drop_index('idx_user_read_deleted', table_name='notifications')
    op.drop_index('idx_user_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
