"""fix_content_title_slug_per_workspace_uniqueness

Revision ID: a57efe654da1
Revises: b1cb9cccd3cc
Create Date: 2026-02-10 13:38:55.147826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""fix_content_title_slug_per_workspace_uniqueness

Revision ID: a57efe654da1
Revises: b1cb9cccd3cc
Create Date: 2026-02-10 13:38:55.147826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a57efe654da1'
down_revision: Union[str, Sequence[str], None] = 'b1cb9cccd3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_title_key', 'content', type_='unique')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=False)
    op.create_unique_constraint('uq_content_workspace_slug', 'content', ['workspace_id', 'slug'])
    op.create_unique_constraint('uq_content_workspace_title', 'content', ['workspace_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_content_workspace_title', 'content', type_='unique')
    op.drop_constraint('uq_content_workspace_slug', 'content', type_='unique')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=True)
    op.create_unique_constraint('content_title_key', 'content', ['title'])
    # ### end Alembic commands ###
