"""add_license_activation_composite_indexes

Revision ID: b1cb9cccd3cc
Revises: 186a1a50dd28
Create Date: 2026-02-10 13:19:15.547754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_license_activation_composite_indexes

Revision ID: b1cb9cccd3cc
Revises: 186a1a50dd28
Create Date: 2026-02-10 13:19:15.547754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1cb9cccd3cc'
down_revision: Union[str, Sequence[str], None] = '186a1a50dd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_license_activations_active', 'license_activations', ['license_id', 'is_active'], unique=False)
    op.create_index('idx_license_activations_license_instance', 'license_activations', ['license_id', 'instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_license_activations_license_instance', table_name='license_activations')
    op.drop_index('idx_license_activations_active', table_name='license_activations')
    # ### end Alembic commands ###
