"""add cancellation_reason to user_subscriptions

Revision ID: c9893663dd80
Revises: merge_20260210
Create Date: 2026-02-12 00:53:01.715320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9893663dd80'
down_revision: Union[str, Sequence[str], None] = 'merge_20260210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('cancellation_reason', sa.String(length=500), nullable=True, comment='User-provided reason for cancellation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'cancellation_reason')
    # ### end Alembic commands ###
