"""initial_schema_baseline

Revision ID: cc3bde5553b9
Revises: 
Create Date: 2025-10-01 19:37:59.661122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc3bde5553b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('checkpoints_run_id_idx'), table_name='checkpoints')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('run_event_run_id_idx'), table_name='run_event')
    op.drop_table('run_event')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_table('assistant')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_table('thread')
    op.drop_table('schema_migrations')
    op.drop_table('notifications')
    op.drop_index(op.f('run_assistant_id_idx'), table_name='run')
    op.drop_index(op.f('run_pending_idx'), table_name='run', postgresql_where="(status = 'pending'::text)")
    op.drop_index(op.f('run_thread_id_idx'), table_name='run')
    op.drop_table('run')
    op.create_unique_constraint(None, 'brand_voice', ['id'])
    op.create_foreign_key(None, 'brand_voice', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'knowledge_files', ['id'])
    op.create_foreign_key(None, 'knowledge_files', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'role_permissions', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'text_knowledge', ['id'])
    op.create_foreign_key(None, 'text_knowledge', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('text_knowledge', 'metadata')
    op.create_unique_constraint(None, 'topics', ['id'])
    op.create_unique_constraint(None, 'user_invitations', ['id'])
    op.create_foreign_key(None, 'user_invitations', 'workspace', ['workspace_id'], ['id'])
    op.create_unique_constraint(None, 'user_roles', ['id'])
    op.create_foreign_key(None, 'user_roles', 'workspace', ['workspace_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'website', ['id'])
    op.create_foreign_key(None, 'website', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'workspace', ['id'])
    op.create_unique_constraint(None, 'workspace_members', ['id'])
    op.create_foreign_key(None, 'workspace_members', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='unique')
    op.drop_constraint(None, 'workspace', type_='unique')
    op.drop_constraint(None, 'website', type_='foreignkey')
    op.drop_constraint(None, 'website', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.drop_constraint(None, 'user_invitations', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.add_column('text_knowledge', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'text_knowledge', type_='foreignkey')
    op.drop_constraint(None, 'text_knowledge', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'role_permissions', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'knowledge_files', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_files', type_='unique')
    op.drop_constraint(None, 'brand_voice', type_='foreignkey')
    op.drop_constraint(None, 'brand_voice', type_='unique')
    op.create_table('run',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assistant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('kwargs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant.assistant_id'], name='run_assistant_id_fkey'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.thread_id'], name='run_thread_id_fkey'),
    sa.PrimaryKeyConstraint('run_id', name='run_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('run_thread_id_idx'), 'run', ['thread_id'], unique=False)
    op.create_index(op.f('run_pending_idx'), 'run', ['created_at'], unique=False, postgresql_where="(status = 'pending'::text)")
    op.create_index(op.f('run_assistant_id_idx'), 'run', ['assistant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dirty', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey'))
    )
    op.create_table('thread',
    sa.Column('thread_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', name='thread_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('assistant',
    sa.Column('assistant_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('graph_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('assistant_id', name='assistant_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('run_event',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('span_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.run_id'], name=op.f('run_event_run_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('run_event_pkey'))
    )
    op.create_index(op.f('run_event_run_id_idx'), 'run_event', ['run_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.run_id'], name=op.f('checkpoints_run_id_fkey')),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_index(op.f('checkpoints_run_id_idx'), 'checkpoints', ['run_id'], unique=False)
    # ### end Alembic commands ###
