"""initial_schema_baseline

Revision ID: cc3bde5553b9
Revises: 
Create Date: 2025-10-01 19:37:59.661122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc3bde5553b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Create all core tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: These DROP commands are for LangGraph tables that may not exist in fresh databases
    # Using execute with IF EXISTS to make this migration safe for both existing and fresh databases
    op.execute('DROP INDEX IF EXISTS checkpoints_run_id_idx')
    op.execute('DROP INDEX IF EXISTS checkpoints_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoints CASCADE')
    op.execute('DROP INDEX IF EXISTS run_event_run_id_idx')
    op.execute('DROP TABLE IF EXISTS run_event CASCADE')
    op.execute('DROP INDEX IF EXISTS checkpoint_blobs_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoint_blobs CASCADE')
    op.execute('DROP TABLE IF EXISTS assistant CASCADE')
    op.execute('DROP INDEX IF EXISTS checkpoint_writes_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS checkpoint_writes CASCADE')
    op.execute('DROP TABLE IF EXISTS checkpoint_migrations CASCADE')
    op.execute('DROP TABLE IF EXISTS thread CASCADE')
    op.execute('DROP TABLE IF EXISTS schema_migrations CASCADE')
    op.execute('DROP TABLE IF EXISTS notifications CASCADE')
    op.execute('DROP INDEX IF EXISTS run_assistant_id_idx')
    op.execute('DROP INDEX IF EXISTS run_pending_idx')
    op.execute('DROP INDEX IF EXISTS run_thread_id_idx')
    op.execute('DROP TABLE IF EXISTS run CASCADE')

    # CREATE CORE TABLES
    # Check if tables exist before creating them (idempotent)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    # Create users table if it doesn't exist (without avatar_url - added in later migration)
    if 'users' not in tables:
        op.create_table('users',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('username', sa.String(length=100), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('first_name', sa.String(length=100), nullable=True),
            sa.Column('last_name', sa.String(length=100), nullable=True),
            sa.Column('display_name', sa.String(length=200), nullable=True),
            sa.Column('password_changed_at', sa.TIMESTAMP(), nullable=True),
            sa.Column('locked_until', sa.TIMESTAMP(), nullable=True),
            sa.Column('reset_token', sa.Text(), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('email_verified', sa.Boolean(), nullable=True),
            sa.Column('email_verified_at', sa.TIMESTAMP(), nullable=True),
            sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
            sa.Column('login_count', sa.Integer(), nullable=True),
            sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
            sa.Column('language', sa.String(length=10), nullable=True),
            sa.Column('timezone', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
            sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
            sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email'),
            sa.UniqueConstraint('id'),
            sa.UniqueConstraint('username')
        )

    # Create workspace table if it doesn't exist
    if 'workspace' not in tables:
        op.create_table('workspace',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('slug', sa.String(), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('url', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id'),
            sa.UniqueConstraint('slug')
        )
        op.create_index(op.f('ix_workspace_slug'), 'workspace', ['slug'], unique=True)

    # Create roles table if it doesn't exist
    if 'roles' not in tables:
        op.create_table('roles',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('display_name', sa.String(length=150), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('hierarchy_level', sa.Integer(), nullable=True),
            sa.Column('is_system_role', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
            sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id')
        )

    # Create permissions table if it doesn't exist
    if 'permissions' not in tables:
        op.create_table('permissions',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=150), nullable=False),
            sa.Column('display_name', sa.String(length=200), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('resource', sa.String(length=50), nullable=True),
            sa.Column('action', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id')
        )

    # Create role_permissions table if it doesn't exist
    if 'role_permissions' not in tables:
        op.create_table('role_permissions',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('permission_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
            sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id')
        )

    # Create user_invitations table if it doesn't exist
    if 'user_invitations' not in tables:
        op.create_table('user_invitations',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('invited_by_user_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('invitation_token', sa.String(length=255), nullable=False),
            sa.Column('status', sa.String(length=50), nullable=True),
            sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
            sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
            sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email', 'workspace_id', name='uq_email_workspace'),
            sa.UniqueConstraint('id'),
            sa.UniqueConstraint('invitation_token')
        )

    # Create user_roles table if it doesn't exist
    if 'user_roles' not in tables:
        op.create_table('user_roles',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('assigned_by_user_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('is_primary', sa.Boolean(), nullable=True),
            sa.Column('assigned_at', sa.TIMESTAMP(), nullable=False),
            sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id')
        )

    # Create workspace_members table if it doesn't exist
    if 'workspace_members' not in tables:
        op.create_table('workspace_members',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('invitation_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=True),
            sa.Column('is_default', sa.Boolean(), nullable=True),
            sa.Column('joined_at', sa.TIMESTAMP(), nullable=False),
            sa.Column('last_activity_at', sa.TIMESTAMP(), nullable=True),
            sa.ForeignKeyConstraint(['invitation_id'], ['user_invitations.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id')
        )

    # Create topics table if it doesn't exist
    if 'topics' not in tables:
        op.create_table('topics',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('topic_name', sa.String(), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('id')
        )

    # Re-fetch table list after creation
    tables = inspector.get_table_names()

    if 'brand_voice' in tables:
        op.create_unique_constraint(None, 'brand_voice', ['id'])
        op.create_foreign_key(None, 'brand_voice', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    if 'knowledge_files' in tables:
        op.create_unique_constraint(None, 'knowledge_files', ['id'])
        op.create_foreign_key(None, 'knowledge_files', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    if 'permissions' in tables:
        op.create_unique_constraint(None, 'permissions', ['id'])
    if 'role_permissions' in tables:
        op.create_unique_constraint(None, 'role_permissions', ['id'])
    if 'roles' in tables:
        op.create_unique_constraint(None, 'roles', ['id'])
    if 'text_knowledge' in tables:
        op.create_unique_constraint(None, 'text_knowledge', ['id'])
        op.create_foreign_key(None, 'text_knowledge', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        # Drop metadata column if it exists
        columns = [c['name'] for c in inspector.get_columns('text_knowledge')]
        if 'metadata' in columns:
            op.drop_column('text_knowledge', 'metadata')
    if 'topics' in tables:
        op.create_unique_constraint(None, 'topics', ['id'])
    if 'user_invitations' in tables:
        op.create_unique_constraint(None, 'user_invitations', ['id'])
        op.create_foreign_key(None, 'user_invitations', 'workspace', ['workspace_id'], ['id'])
    if 'user_roles' in tables:
        op.create_unique_constraint(None, 'user_roles', ['id'])
        op.create_foreign_key(None, 'user_roles', 'workspace', ['workspace_id'], ['id'])
    if 'users' in tables:
        op.create_unique_constraint(None, 'users', ['id'])
    if 'website' in tables:
        op.create_unique_constraint(None, 'website', ['id'])
        op.create_foreign_key(None, 'website', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    if 'workspace' in tables:
        op.create_unique_constraint(None, 'workspace', ['id'])
    if 'workspace_members' in tables:
        op.create_unique_constraint(None, 'workspace_members', ['id'])
        op.create_foreign_key(None, 'workspace_members', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='unique')
    op.drop_constraint(None, 'workspace', type_='unique')
    op.drop_constraint(None, 'website', type_='foreignkey')
    op.drop_constraint(None, 'website', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint(None, 'user_invitations', type_='foreignkey')
    op.drop_constraint(None, 'user_invitations', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.add_column('text_knowledge', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'text_knowledge', type_='foreignkey')
    op.drop_constraint(None, 'text_knowledge', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'role_permissions', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'knowledge_files', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_files', type_='unique')
    op.drop_constraint(None, 'brand_voice', type_='foreignkey')
    op.drop_constraint(None, 'brand_voice', type_='unique')
    op.create_table('run',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assistant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('kwargs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant.assistant_id'], name='run_assistant_id_fkey'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.thread_id'], name='run_thread_id_fkey'),
    sa.PrimaryKeyConstraint('run_id', name='run_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('run_thread_id_idx'), 'run', ['thread_id'], unique=False)
    op.create_index(op.f('run_pending_idx'), 'run', ['created_at'], unique=False, postgresql_where="(status = 'pending'::text)")
    op.create_index(op.f('run_assistant_id_idx'), 'run', ['assistant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dirty', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey'))
    )
    op.create_table('thread',
    sa.Column('thread_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', name='thread_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('assistant',
    sa.Column('assistant_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('graph_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('assistant_id', name='assistant_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('run_event',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('span_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.run_id'], name=op.f('run_event_run_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('run_event_pkey'))
    )
    op.create_index(op.f('run_event_run_id_idx'), 'run_event', ['run_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.run_id'], name=op.f('checkpoints_run_id_fkey')),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_index(op.f('checkpoints_run_id_idx'), 'checkpoints', ['run_id'], unique=False)
    # ### end Alembic commands ###
