"""add promotions and credit grants

Revision ID: cd6b868bf9d7
Revises: e52e15b5c2ea
Create Date: 2026-10-06 13:21:42.538962

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd6b868bf9d7"
down_revision: Union[str, Sequence[str], None] = "e52e15b5c2ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=32), server_default="bonus_credits", nullable=False),
        sa.Column("credit_multiplier", sa.Integer(), nullable=True),
        sa.Column("bonus_credits", sa.Integer(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("plan_names", postgresql.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("billing_periods", postgresql.ARRAY(sa.String(length=20)), nullable=True),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('bonus_credits')", name="ck_promotions_kind"),
        sa.CheckConstraint(
            "(credit_multiplier IS NOT NULL AND credit_multiplier > 1 AND bonus_credits IS NULL) OR (bonus_credits IS NOT NULL AND bonus_credits > 0 AND credit_multiplier IS NULL)",
            name="ck_promotions_bonus",
        ),
        sa.CheckConstraint(
            "max_redemptions IS NULL OR max_redemptions > 0", name="ck_promotions_max_redemptions"
        ),
        sa.CheckConstraint("starts_at < ends_at", name="ck_promotions_window"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "credit_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("promotion_id", sa.UUID(), nullable=False),
        sa.Column("lemonsqueezy_order_id", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("remaining", sa.Integer(), nullable=False),
        sa.Column("forfeited", sa.Integer(), server_default="0", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "remaining >= 0 AND forfeited >= 0 AND remaining + forfeited <= amount",
            name="ck_credit_grants_remaining",
        ),
        sa.ForeignKeyConstraint(["promotion_id"], ["promotions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["subscription_id"], ["user_subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subscription_id", "promotion_id", name="uq_credit_grants_subscription_promotion"
        ),
    )
    op.create_index(
        op.f("ix_credit_grants_lemonsqueezy_order_id"),
        "credit_grants",
        ["lemonsqueezy_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_grants_promotion_id"), "credit_grants", ["promotion_id"], unique=False
    )
    op.create_index(
        op.f("ix_credit_grants_subscription_id"), "credit_grants", ["subscription_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credit_grants_subscription_id"), table_name="credit_grants")
    op.drop_index(op.f("ix_credit_grants_promotion_id"), table_name="credit_grants")
    op.drop_index(op.f("ix_credit_grants_lemonsqueezy_order_id"), table_name="credit_grants")
    op.drop_table("credit_grants")
    op.drop_table("promotions")
    # ### end Alembic commands ###
