"""Added Internal Links

Revision ID: d1e70992e366
Revises: 9a9a7e36e5e0
Create Date: 2026-05-14 17:04:24.173546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1e70992e366'
down_revision: Union[str, Sequence[str], None] = '9a9a7e36e5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_publishing_results',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('wp_post_id', sa.Integer(), nullable=True),
    sa.Column('shopify_article_id', sa.BigInteger(), nullable=True),
    sa.Column('shopify_blog_id', sa.BigInteger(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'site_id', name='uq_content_publishing_result_content_site'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_content_publishing_results_content_id'), 'content_publishing_results', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_publishing_results_site_id'), 'content_publishing_results', ['site_id'], unique=False)
    op.drop_index(op.f('ix_content_topic_id'), table_name='content')
    op.drop_constraint(op.f('fk_content_topic_id'), 'content', type_='foreignkey')
    op.drop_column('content', 'topic_id')
    op.drop_index(op.f('ix_topics_workspace_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('vector_migrations')
    op.execute('DROP INDEX IF EXISTS store_vectors_embedding_idx')
    op.drop_table('store_vectors')
    op.drop_index(op.f('idx_store_expires_at'), table_name='store', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('store_prefix_idx'), table_name='store', postgresql_ops={'prefix': 'text_pattern_ops'})
    op.drop_table('store')
    op.drop_table('store_migrations')
    op.alter_column('integrations', 'site_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Integration site URL',
               existing_comment='WordPress site URL',
               existing_nullable=True)
    op.alter_column('integrations', 'api_endpoint',
               existing_type=sa.VARCHAR(length=500),
               comment='Provider-specific API endpoint',
               existing_comment='Rext-AI Plugin Base Endpoint',
               existing_nullable=True)
    op.alter_column('integrations', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Provider username',
               existing_comment='WordPress username',
               existing_nullable=True)
    op.alter_column('integrations', 'app_password',
               existing_type=sa.VARCHAR(),
               comment='Provider application password (encrypted)',
               existing_comment='WordPress application password (encrypted)',
               existing_nullable=True)
    op.alter_column('integrations', 'api_key',
               existing_type=sa.VARCHAR(),
               comment='Provider API key or token (encrypted)',
               existing_comment='WordPress Rext-AI API Key (encrypted)',
               existing_nullable=True)
    op.alter_column('persona', 'areas_of_expertise',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='areas_of_expertise::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    from sqlalchemy import inspect as sa_inspect
    conn = op.get_bind()
    inspector = sa_inspect(conn)
    existing_tables = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persona', 'areas_of_expertise',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('integrations', 'api_key',
               existing_type=sa.VARCHAR(),
               comment='WordPress Rext-AI API Key (encrypted)',
               existing_comment='Provider API key or token (encrypted)',
               existing_nullable=True)
    op.alter_column('integrations', 'app_password',
               existing_type=sa.VARCHAR(),
               comment='WordPress application password (encrypted)',
               existing_comment='Provider application password (encrypted)',
               existing_nullable=True)
    op.alter_column('integrations', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='WordPress username',
               existing_comment='Provider username',
               existing_nullable=True)
    op.alter_column('integrations', 'api_endpoint',
               existing_type=sa.VARCHAR(length=500),
               comment='Rext-AI Plugin Base Endpoint',
               existing_comment='Provider-specific API endpoint',
               existing_nullable=True)
    op.alter_column('integrations', 'site_url',
               existing_type=sa.VARCHAR(length=500),
               comment='WordPress site URL',
               existing_comment='Integration site URL',
               existing_nullable=True)
    if 'store_migrations' not in existing_tables:
        op.create_table('store_migrations',
        sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
        )
    if 'store' not in existing_tables:
        op.create_table('store',
        sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('prefix', 'key', name=op.f('store_pkey'))
        )
        op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, postgresql_ops={'prefix': 'text_pattern_ops'})
        op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    if 'store_vectors' not in existing_tables:
        op.create_table('store_vectors',
        sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('field_name', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['prefix', 'key'], ['store.prefix', 'store.key'], name=op.f('store_vectors_prefix_key_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('prefix', 'key', 'field_name', name=op.f('store_vectors_pkey'))
        )
    if 'vector_migrations' not in existing_tables:
        op.create_table('vector_migrations',
        sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('v', name=op.f('vector_migrations_pkey'))
        )
    if 'topics' not in existing_tables:
        op.create_table('topics',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('generated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column('generated_by_first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('generated_by_last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('angle', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('channel_fit', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
        sa.Column('audience_fit', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
        sa.Column('why_it_works', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column('suggested_defaults', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('goal_alignment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('content_guidance', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('audience_insights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('internal_research_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('user_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], name=op.f('topics_generated_by_user_id_fkey'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('topics_workspace_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey'))
        )
        op.create_index(op.f('ix_topics_workspace_id'), 'topics', ['workspace_id'], unique=False)
    content_cols = {c['name'] for c in inspector.get_columns('content')}
    if 'topic_id' not in content_cols:
        op.add_column('content', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=True))
        op.create_foreign_key(op.f('fk_content_topic_id'), 'content', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
        op.create_index(op.f('ix_content_topic_id'), 'content', ['topic_id'], unique=False)
    if 'content_publishing_results' in existing_tables:
        op.drop_index(op.f('ix_content_publishing_results_site_id'), table_name='content_publishing_results')
        op.drop_index(op.f('ix_content_publishing_results_content_id'), table_name='content_publishing_results')
        op.drop_table('content_publishing_results')
    # ### end Alembic commands ###
