"""add avatar_url to users table

Revision ID: d28b3fe4efb9
Revises: 3e8d832f695c
Create Date: 2025-10-02 15:10:34.154301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28b3fe4efb9'
down_revision: Union[str, Sequence[str], None] = '3e8d832f695c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_blacklist_expires_at', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index('idx_token_blacklist_jti', 'token_blacklist', ['jti'], unique=False)
    op.create_index('idx_token_blacklist_user_id', 'token_blacklist', ['user_id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'audit_logs', ['id'])
    op.drop_index(op.f('idx_permissions_name'), table_name='permissions')
    op.drop_index(op.f('idx_permissions_resource_action'), table_name='permissions')
    op.drop_index(op.f('idx_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('idx_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('idx_roles_is_system_role'), table_name='roles')
    op.drop_index(op.f('idx_roles_name'), table_name='roles')
    op.create_unique_constraint(None, 'subscription_plans', ['id'])
    op.drop_index(op.f('idx_user_invitations_email'), table_name='user_invitations')
    op.drop_index(op.f('idx_user_invitations_expires_at'), table_name='user_invitations')
    op.drop_index(op.f('idx_user_invitations_status'), table_name='user_invitations')
    op.drop_index(op.f('idx_user_invitations_token'), table_name='user_invitations')
    op.drop_index(op.f('idx_user_invitations_workspace_id'), table_name='user_invitations')
    op.drop_index(op.f('idx_user_roles_is_primary'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_workspace_id'), table_name='user_roles')
    op.create_unique_constraint(None, 'user_subscriptions', ['id'])
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('idx_users_deleted_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_email_verified'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_index(op.f('idx_workspace_name'), table_name='workspace')
    op.drop_index(op.f('idx_workspace_user_id'), table_name='workspace')
    op.drop_index(op.f('idx_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('idx_workspace_members_workspace_id'), table_name='workspace_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_workspace_user_id'), 'workspace', ['user_id'], unique=False)
    op.create_index(op.f('idx_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('idx_users_email_verified'), 'users', ['email_verified'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'user_subscriptions', type_='unique')
    op.create_index(op.f('idx_user_roles_workspace_id'), 'user_roles', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('idx_user_roles_is_primary'), 'user_roles', ['is_primary'], unique=False)
    op.create_index(op.f('idx_user_invitations_workspace_id'), 'user_invitations', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_user_invitations_token'), 'user_invitations', ['invitation_token'], unique=False)
    op.create_index(op.f('idx_user_invitations_status'), 'user_invitations', ['status'], unique=False)
    op.create_index(op.f('idx_user_invitations_expires_at'), 'user_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('idx_user_invitations_email'), 'user_invitations', ['email'], unique=False)
    op.drop_constraint(None, 'subscription_plans', type_='unique')
    op.create_index(op.f('idx_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('idx_roles_is_system_role'), 'roles', ['is_system_role'], unique=False)
    op.create_index(op.f('idx_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('idx_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('idx_permissions_resource_action'), 'permissions', ['resource', 'action'], unique=False)
    op.create_index(op.f('idx_permissions_name'), 'permissions', ['name'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='unique')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_user_id', table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_jti', table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_expires_at', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
