"""add favicon url to workspace

Revision ID: dbca2aff6679
Revises: 3c9e1e5d5028
Create Date: 2026-10-06 04:41:38.020942

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbca2aff6679"
down_revision: Union[str, Sequence[str], None] = "3c9e1e5d5028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("favicon_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "favicon_url")
    # ### end Alembic commands ###
