"""standardize_soft_delete_columns

Revision ID: dd1491b13c9a
Revises: 8791495e5b59
Create Date: 2026-02-10 18:13:10.718931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd1491b13c9a'
down_revision: Union[str, Sequence[str], None] = '8791495e5b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('integrations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('media', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('media', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'archived_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'email_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'sse_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When this notification should expire and be auto-archived',
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('idx_user_read_deleted'), table_name='notifications')
    op.create_index('idx_user_read_deleted', 'notifications', ['user_id', 'is_read', 'deleted_at'], unique=False)
    op.drop_column('notifications', 'is_deleted')
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('workspace', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.add_column('notifications', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('idx_user_read_deleted', table_name='notifications')
    op.create_index(op.f('idx_user_read_deleted'), 'notifications', ['user_id', 'is_read', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.alter_column('notifications', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notifications', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When this notification should expire and be auto-archived',
               existing_nullable=True)
    op.alter_column('notifications', 'sse_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'email_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'archived_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('media', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment='Soft delete timestamp',
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('media', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('integrations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    op.alter_column('content', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               comment=None,
               existing_comment='Soft delete timestamp. NULL = active, non-NULL = deleted.',
               existing_nullable=True)
    # ### end Alembic commands ###
