"""subscription status from Lemon Squeezy: labels match the enum, UNPAID, provider_updated_at

Revision ID: e52e15b5c2ea
Revises: dbca2aff6679
Create Date: 2026-10-06 09:17:05.640437

The subscriptionstatus type held 'past_due' and 'paused' while SQLAlchemy writes
the member names, so every write or query naming PAST_DUE or PAUSED failed. They
are renamed to the names, UNPAID is added (Lemon Squeezy's status once its
payment retries run out), and the rows the old 7-day grace left SUSPENDED become
PAST_DUE: Lemon Squeezy's own status decides access from now on.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52e15b5c2ea'
down_revision: Union[str, Sequence[str], None] = 'dbca2aff6679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE subscriptionstatus RENAME VALUE 'past_due' TO 'PAST_DUE'")
    op.execute("ALTER TYPE subscriptionstatus RENAME VALUE 'paused' TO 'PAUSED'")
    # A label added in a transaction can't be used in it; nothing below uses it.
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'UNPAID' AFTER 'PAST_DUE'")
    # The old grace wrote SUSPENDED with its deadline in grace_period_end (the
    # payment-failed webhook, and the local stack's seeded past-due account).
    op.execute(
        "UPDATE user_subscriptions SET status = 'PAST_DUE' "
        "WHERE status = 'SUSPENDED' AND grace_period_end IS NOT NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('provider_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    PostgreSQL can't drop an enum label, so UNPAID stays in the type, unused: the
    code before this stored Lemon Squeezy's "unpaid" as PAST_DUE, and so do the
    rows here. Rows moved from SUSPENDED stay PAST_DUE.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'provider_updated_at')
    # ### end Alembic commands ###
    op.execute("UPDATE user_subscriptions SET status = 'PAST_DUE' WHERE status = 'UNPAID'")
    op.execute("ALTER TYPE subscriptionstatus RENAME VALUE 'PAUSED' TO 'paused'")
    op.execute("ALTER TYPE subscriptionstatus RENAME VALUE 'PAST_DUE' TO 'past_due'")
