"""simplify_topics

Revision ID: f3aa0ba84da7
Revises: e2e8b871381e
Create Date: 2026-03-18 11:29:10.889999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision: str = 'f3aa0ba84da7'
down_revision: Union[str, Sequence[str], None] = 'e2e8b871381e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('topic_name', sa.String(), nullable=False))
    op.alter_column('topics', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'topics', ['id'])
    op.drop_column('topics', 'user_settings')
    op.drop_column('topics', 'audience_insights')
    op.drop_column('topics', 'tags')
    op.drop_column('topics', 'title')
    op.drop_column('topics', 'angle')
    op.drop_column('topics', 'suggested_defaults')
    op.drop_column('topics', 'goal_alignment')
    op.drop_column('topics', 'approved')
    op.drop_column('topics', 'why_it_works')
    op.drop_column('topics', 'channel_fit')
    op.drop_column('topics', 'generated_by_last_name')
    op.drop_column('topics', 'scores')
    op.drop_column('topics', 'approved_at')
    op.drop_column('topics', 'audience_fit')
    op.drop_column('topics', 'content_guidance')
    op.drop_column('topics', 'internal_research_config')
    op.drop_column('topics', 'generated_by_first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('generated_by_first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('internal_research_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('content_guidance', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('audience_fit', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('generated_by_last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('channel_fit', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('why_it_works', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('goal_alignment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('suggested_defaults', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('angle', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('audience_insights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('topics', sa.Column('user_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'topics', type_='unique')
    op.alter_column('topics', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('topics', 'topic_name')
    # ### end Alembic commands ###
