from typing import Union

from .commercial import (
    AlternativesOutlineState,
    BestToolsOutlineState,
    BuyingGuideOutlineState,
    ComparisonOutlineState,
    InDepthReviewOutlineState,
    ProductRoundupOutlineState,
    ProsConsOutlineState,
)
from .informational import (
    BlogOutline,
    CaseStudyOutline,
    ChecklistOutline,
    ExplainerOutline,
    FAQOutline,
    GlossaryOutline,
    HowToGuideOutline,
    PillarContentOutline,
    ResourceListOutline,
    TutorialOutline,
    WhitePaperOutline,
)
from .navigational import (
    AboutUsOutlineState,
    BrandPageOutlineState,
    ContactUsOutlineState,
    DocumentationOutlineState,
    FeatureOverviewOutlineState,
    HelpCenterOutlineState,
    LoginGuideOutlineState,
    ProductHomepageOutlineState,
)
from .transactional import (
    CheckoutPageOutlineState,
    CouponPageOutlineState,
    DemoPageOutlineState,
    LandingPageOutlineState,
    PricingPageOutlineState,
    SalesPageOutlineState,
    ServicePageOutlineState,
    SignupPageOutlineState,
)

OutlineState = Union[
    # Informational
    BlogOutline,
    HowToGuideOutline,
    ExplainerOutline,
    PillarContentOutline,
    ChecklistOutline,
    TutorialOutline,
    FAQOutline,
    WhitePaperOutline,
    CaseStudyOutline,
    GlossaryOutline,
    ResourceListOutline,
    # Commercial
    ComparisonOutlineState,
    BestToolsOutlineState,
    AlternativesOutlineState,
    InDepthReviewOutlineState,
    ProsConsOutlineState,
    ProductRoundupOutlineState,
    BuyingGuideOutlineState,
    # Navigational
    BrandPageOutlineState,
    ProductHomepageOutlineState,
    FeatureOverviewOutlineState,
    DocumentationOutlineState,
    LoginGuideOutlineState,
    ContactUsOutlineState,
    AboutUsOutlineState,
    HelpCenterOutlineState,
    # Transactional
    SalesPageOutlineState,
    PricingPageOutlineState,
    SignupPageOutlineState,
    DemoPageOutlineState,
    CouponPageOutlineState,
    CheckoutPageOutlineState,
    LandingPageOutlineState,
    ServicePageOutlineState,
]

__all__ = [
    "OutlineState",
    # Informational
    "BlogOutline",
    "HowToGuideOutline",
    "ExplainerOutline",
    "PillarContentOutline",
    "ChecklistOutline",
    "TutorialOutline",
    "FAQOutline",
    "WhitePaperOutline",
    "CaseStudyOutline",
    "GlossaryOutline",
    "ResourceListOutline",
    # Commercial
    "ComparisonOutlineState",
    "BestToolsOutlineState",
    "AlternativesOutlineState",
    "InDepthReviewOutlineState",
    "ProsConsOutlineState",
    "ProductRoundupOutlineState",
    "BuyingGuideOutlineState",
    # Navigational
    "BrandPageOutlineState",
    "ProductHomepageOutlineState",
    "FeatureOverviewOutlineState",
    "DocumentationOutlineState",
    "LoginGuideOutlineState",
    "ContactUsOutlineState",
    "AboutUsOutlineState",
    "HelpCenterOutlineState",
    # Transactional
    "SalesPageOutlineState",
    "PricingPageOutlineState",
    "SignupPageOutlineState",
    "DemoPageOutlineState",
    "CouponPageOutlineState",
    "CheckoutPageOutlineState",
    "LandingPageOutlineState",
    "ServicePageOutlineState",
]
