"""Keeps `.env.example` true to the code: every environment name the backend reads, and no other.

`.env.example` has two parts:
- above the marker line, the names a person sets first, written by hand with their notes;
- below it, every other setting, generated here from the settings classes (pydantic-settings) and
  from the code's direct reads (`os.getenv`, `os.environ`), each with its default and description.

    uv run python scripts/env_example.py           # rewrite the generated part
    uv run python scripts/env_example.py --check   # exit 1 when it's out of date, or the hand-written
                                                   # part names something nothing reads

The code is read with `ast`, never imported, so nothing here touches `.env` or a database.
"""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXAMPLE = ROOT / ".env.example"
MARKER = "# ---- Generated by scripts/env_example.py from here on; edit the settings, not these lines ----"

DIRECT_READ_DIRS = ["src", "scripts", "alembic"]
DIRECT_READ_FILES = ["main.py", "server.py", "migrate.py"]

# Names the code doesn't read by a literal name, kept in the hand-written part.
EXTERNAL = {
    "DATABASE_URI": "the LangGraph runtime's database; migrate_on_start reads it by a loop",
    "REDIS_URI": "the LangGraph runtime's Redis",
    "TAVILY_API_KEY": "read by langchain-tavily",
    "PGBOUNCER_HOST": "documented for when the app goes through PgBouncer",
}
# The per-plan Lemon Squeezy IDs, read by a name built from each plan's name
# (src/config/lemonsqueezy_plan_config.py), for the plans scripts/seeds/ creates.
PLAN_TOKENS = ("STARTER", "GROWTH", "PRO", "AGENCY")
PLAN_NAMES = {
    f"LEMONSQUEEZY_{plan}_{key}": key
    for plan in PLAN_TOKENS
    for key in ("PRODUCT_ID", "VARIANT_ID_MONTHLY", "VARIANT_ID_YEARLY", "STORE_ID")
}
# A secret's default never goes into the example.
SECRET = re.compile(r"(SECRET|PASSWORD|_KEY$|_KEY_ID$|TOKEN|DSN)")

NAME_LINE = re.compile(r"^#?\s*([A-Z][A-Z0-9_]+)=", re.M)


def _literal(node: ast.AST | None):
    if node is None:
        return None, False
    try:
        return ast.literal_eval(node), True
    except ValueError:
        return None, False


_OPS = {
    ast.Add: lambda a, b: a + b,
    ast.Sub: lambda a, b: a - b,
    ast.Mult: lambda a, b: a * b,
    ast.FloorDiv: lambda a, b: a // b,
    ast.Div: lambda a, b: a / b,
    ast.Pow: lambda a, b: a**b,
}


def _default(node: ast.AST | None, constants: dict):
    """A default's value, when the code makes it from literals: a literal, arithmetic on literals or
    on the module's literal constants, or `os.getenv(name, fallback)` (its fallback). Else unknown."""
    if node is None:
        return None, False
    value, ok = _literal(node)
    if ok:
        return value, True
    if isinstance(node, ast.Name) and node.id in constants:
        return constants[node.id], True
    if isinstance(node, ast.BinOp) and type(node.op) in _OPS:
        left, ok_left = _default(node.left, constants)
        right, ok_right = _default(node.right, constants)
        if ok_left and ok_right:
            try:
                return _OPS[type(node.op)](left, right), True
            except (TypeError, ZeroDivisionError):
                return None, False
    for inner in ast.walk(node):
        f = getattr(inner, "func", None)
        if (
            isinstance(f, ast.Attribute)
            and f.attr == "getenv"
            and getattr(f.value, "id", None) == "os"
            and len(inner.args) > 1
        ):
            return _literal(inner.args[1])
    return None, False


def _module_constants(tree: ast.Module) -> dict:
    constants: dict = {}
    for item in tree.body:
        if isinstance(item, ast.Assign) and len(item.targets) == 1:
            target = item.targets[0]
            if isinstance(target, ast.Name):
                value, ok = _default(item.value, constants)
                if ok:
                    constants[target.id] = value
    return constants


def _is_settings(cls: ast.ClassDef) -> bool:
    return any(
        (isinstance(b, ast.Name) and b.id == "BaseSettings")
        or (isinstance(b, ast.Attribute) and b.attr == "BaseSettings")
        for b in cls.bases
    )


def settings_files() -> list[str]:
    """Every file under src/ with a settings class, the main one first."""
    found = []
    for path in sorted((ROOT / "src").rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        if any(isinstance(n, ast.ClassDef) and _is_settings(n) for n in tree.body):
            found.append(str(path.relative_to(ROOT)))
    return sorted(found, key=lambda rel: (rel != "src/api/config.py", rel))


def _env_value(value) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, dict, set, tuple)):
        return json.dumps(list(value) if isinstance(value, (set, tuple)) else value)
    return str(value)


def settings_fields() -> list[tuple[str, str, list[tuple[str, str | None, bool, str, str]]]]:
    """(file, class, [(name, default text or None when the code computes it, required,
    description, annotation)])."""
    sections = []
    for rel in settings_files():
        tree = ast.parse((ROOT / rel).read_text(encoding="utf-8"))
        constants = _module_constants(tree)
        for cls in [n for n in tree.body if isinstance(n, ast.ClassDef)]:
            if not _is_settings(cls):
                continue
            # A case-sensitive class reads its fields' names as written; the others match any case.
            case_sensitive = any(
                isinstance(item, ast.Assign)
                and any(getattr(t, "id", None) == "model_config" for t in item.targets)
                and isinstance(item.value, ast.Call)
                and any(
                    k.arg == "case_sensitive" and _literal(k.value)[0] is True
                    for k in item.value.keywords
                )
                for item in cls.body
            )
            fields = []
            for item in cls.body:
                if not (isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name)):
                    continue
                name = item.target.id
                if name == "model_config" or name.startswith("_"):
                    continue
                description, default, known, required, env = "", None, True, False, name
                value = item.value
                if isinstance(value, ast.Call) and getattr(value.func, "id", None) == "Field":
                    keywords = {k.arg: k.value for k in value.keywords if k.arg}
                    if "description" in keywords:
                        description, _ = _literal(keywords["description"])
                    for key in ("validation_alias", "alias"):
                        if key in keywords:
                            alias, ok = _literal(keywords[key])
                            if ok and isinstance(alias, str):
                                env = alias
                    raw = keywords.get("default", value.args[0] if value.args else None)
                    if isinstance(raw, ast.Constant) and raw.value is Ellipsis:
                        required = True
                    elif "default_factory" in keywords:
                        known = False
                    elif raw is None:
                        required = "default" not in keywords and not value.args
                    else:
                        default, known = _default(raw, constants)
                elif value is None:
                    required = True
                else:
                    default, known = _default(value, constants)
                if SECRET.search(env.upper()):
                    default, known = None, True
                text = _env_value(default) if known else None
                annotation = ast.unparse(item.annotation)
                fields.append(
                    (
                        env if case_sensitive else env.upper(),
                        text,
                        required,
                        description or "",
                        annotation,
                    )
                )
            sections.append((rel, cls.name, fields))
    return sections


def direct_reads() -> dict[str, tuple[str, str | None]]:
    """name -> (first file that reads it, its literal default or None)."""
    found: dict[str, tuple[str, str | None]] = {}
    paths = [p for d in DIRECT_READ_DIRS for p in sorted((ROOT / d).rglob("*.py"))]
    paths += [ROOT / f for f in DIRECT_READ_FILES if (ROOT / f).exists()]
    for path in paths:
        rel = str(path.relative_to(ROOT))
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            name, default = None, None
            if isinstance(node, ast.Call):
                f = node.func
                if isinstance(f, ast.Attribute) and (
                    (f.attr == "getenv" and getattr(f.value, "id", None) == "os")
                    or (f.attr == "get" and getattr(f.value, "attr", None) == "environ")
                ):
                    if node.args and isinstance(node.args[0], ast.Constant):
                        name = node.args[0].value
                        if len(node.args) > 1:
                            value, ok = _literal(node.args[1])
                            default = _env_value(value) if ok else None
            elif isinstance(node, ast.Subscript) and getattr(node.value, "attr", None) == "environ":
                if isinstance(node.slice, ast.Constant):
                    name = node.slice.value
            if isinstance(name, str) and re.fullmatch(r"[A-Z][A-Z0-9_]+", name):
                if SECRET.search(name):
                    default = None
                found.setdefault(name, (rel, default))
    return found


def generated(head_names: set[str]) -> str:
    lines = [
        MARKER,
        "# Every other setting the code reads, with its default. A commented line is optional; a line",
        "# without # has no default and must be set. Run `uv run python scripts/env_example.py` after",
        "# changing a settings class; tests/unit/test_env_example.py fails while this part is stale.",
    ]
    seen = set(head_names)
    for rel, cls, fields in settings_fields():
        block = []
        for name, text, required, description, _ in fields:
            if name in seen:
                continue
            seen.add(name)
            if description:
                block.append(f"# {description}")
            if required:
                block.append(f"{name}=")
            elif text is None:
                # No `=`: uncommented, a blank value would replace the default the code computes.
                block.append(f"# {name}   (its default is computed in {rel})")
            else:
                block.append(f"# {name}={text}")
        if block:
            lines += ["", f"# {rel} ({cls})", *block]
    rest = [(n, src, d) for n, (src, d) in sorted(direct_reads().items()) if n not in seen]
    if rest:
        lines += ["", "# Read directly (os.getenv / os.environ)"]
        for name, src, default in rest:
            seen.add(name)
            lines.append(f"# {name}={default or ''}   ({src})")
    plans = [name for name in PLAN_NAMES if name not in seen]
    if plans:
        lines += [
            "",
            "# Per plan (src/config/lemonsqueezy_plan_config.py); a plan's STORE_ID falls back to",
            "# LEMONSQUEEZY_STORE_ID when it's sold from the same store",
        ]
        lines += [f"# {name}=" for name in plans]
    return "\n".join(lines) + "\n"


def split_example() -> tuple[str, str]:
    text = EXAMPLE.read_text(encoding="utf-8")
    if MARKER not in text:
        return text.rstrip("\n") + "\n\n", ""
    head, tail = text.split(MARKER, 1)
    return head, MARKER + tail


def head_problems(head: str) -> list[str]:
    fields = [field for _, _, section in settings_fields() for field in section]
    read = {name for name, *_ in fields} | set(direct_reads())
    # A blank value for a number or a flag fails the settings' validation at start.
    typed = {
        name: annotation
        for name, *_, annotation in fields
        if annotation in ("bool", "int", "float")
    }
    problems = []
    for name in sorted(set(NAME_LINE.findall(head))):
        if name not in read and name not in EXTERNAL and name not in PLAN_NAMES:
            problems.append(f".env.example names {name}, which nothing reads: remove it")
    for name in re.findall(r"^([A-Z][A-Z0-9_]+)=\s*$", head, re.M):
        if name in typed:
            problems.append(
                f".env.example leaves {name} blank, which isn't a valid {typed[name]}: "
                "give it a value or comment it out"
            )
    return problems


def main() -> int:
    head, tail = split_example()
    fresh = generated(set(NAME_LINE.findall(head)))
    if "--check" in sys.argv:
        problems = head_problems(head)
        if tail != fresh:
            problems.append(
                ".env.example's generated part is out of date: run `uv run python scripts/env_example.py`"
            )
        for problem in problems:
            print(problem)
        return 1 if problems else 0
    EXAMPLE.write_text(head + fresh, encoding="utf-8")
    print(f"wrote {EXAMPLE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
