"""Keeps `.env.example` true to the code: every environment name the backend reads, and no other.

`.env.example` has two parts:
- above the marker line, the names a person sets first, written by hand with their notes;
- below it, every other setting, generated here from the settings classes (pydantic-settings) and
  from the code's direct reads (`os.getenv`, `os.environ`), each with its default and description.

    uv run python scripts/env_example.py           # rewrite the generated part
    uv run python scripts/env_example.py --check   # exit 1 when it's out of date, or the hand-written
                                                   # part names something nothing reads

The code is read with `ast`, never imported, so nothing here touches `.env` or a database.
"""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXAMPLE = ROOT / ".env.example"
MARKER = "# ---- Generated by scripts/env_example.py from here on; edit the settings, not these lines ----"

SETTINGS_FILES = [
    "src/api/config.py",
    "src/config/email_config.py",
    "src/config/payment_config.py",
    "src/config/storage_config.py",
    "src/config/cleanup_config.py",
]
DIRECT_READ_DIRS = ["src", "scripts", "alembic"]
DIRECT_READ_FILES = ["main.py", "server.py", "migrate.py"]

# Names the code doesn't read by a literal name, kept in the hand-written part.
EXTERNAL = {
    "DATABASE_URI": "the LangGraph runtime's database; migrate_on_start reads it by a loop",
    "REDIS_URI": "the LangGraph runtime's Redis",
    "TAVILY_API_KEY": "read by langchain-tavily",
    "PGBOUNCER_HOST": "documented for when the app goes through PgBouncer",
}
# Per-plan Lemon Squeezy IDs, read by name pattern (src/config/lemonsqueezy_plan_config.py).
DYNAMIC = re.compile(
    r"^LEMONSQUEEZY_(STARTER|GROWTH|PRO|AGENCY)_(PRODUCT_ID|VARIANT_ID_MONTHLY|VARIANT_ID_YEARLY|STORE_ID)$"
)
# A secret's default never goes into the example.
SECRET = re.compile(r"(SECRET|PASSWORD|_KEY$|_KEY_ID$|TOKEN|DSN)")

NAME_LINE = re.compile(r"^#?\s*([A-Z][A-Z0-9_]+)=", re.M)


def _literal(node: ast.AST | None):
    if node is None:
        return None, False
    try:
        return ast.literal_eval(node), True
    except ValueError:
        return None, False


def _env_value(value) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, dict, set, tuple)):
        return json.dumps(list(value) if isinstance(value, (set, tuple)) else value)
    return str(value)


def settings_fields() -> list[tuple[str, str, list[tuple[str, str | None, bool, str]]]]:
    """(file, class, [(name, default text or None when unknown, required, description)])."""
    sections = []
    for rel in SETTINGS_FILES:
        tree = ast.parse((ROOT / rel).read_text(encoding="utf-8"))
        for cls in [n for n in tree.body if isinstance(n, ast.ClassDef)]:
            if not any(
                (isinstance(b, ast.Name) and b.id == "BaseSettings")
                or (isinstance(b, ast.Attribute) and b.attr == "BaseSettings")
                for b in cls.bases
            ):
                continue
            fields = []
            for item in cls.body:
                if not (isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name)):
                    continue
                name = item.target.id
                if name == "model_config" or name.startswith("_"):
                    continue
                description, default, known, required, env = "", None, True, False, name
                value = item.value
                if isinstance(value, ast.Call) and getattr(value.func, "id", None) == "Field":
                    keywords = {k.arg: k.value for k in value.keywords if k.arg}
                    if "description" in keywords:
                        description, _ = _literal(keywords["description"])
                    for key in ("validation_alias", "alias"):
                        if key in keywords:
                            alias, ok = _literal(keywords[key])
                            if ok and isinstance(alias, str):
                                env = alias
                    raw = keywords.get("default", value.args[0] if value.args else None)
                    if isinstance(raw, ast.Constant) and raw.value is Ellipsis:
                        required = True
                    elif "default_factory" in keywords:
                        known = False
                    elif raw is None:
                        required = "default" not in keywords and not value.args
                    else:
                        default, known = _literal(raw)
                elif value is None:
                    required = True
                else:
                    default, known = _literal(value)
                text = _env_value(default) if known and not SECRET.search(env.upper()) else None
                fields.append((env.upper(), text, required, description or ""))
            sections.append((rel, cls.name, fields))
    return sections


def direct_reads() -> dict[str, tuple[str, str | None]]:
    """name -> (first file that reads it, its literal default or None)."""
    found: dict[str, tuple[str, str | None]] = {}
    paths = [p for d in DIRECT_READ_DIRS for p in sorted((ROOT / d).rglob("*.py"))]
    paths += [ROOT / f for f in DIRECT_READ_FILES if (ROOT / f).exists()]
    for path in paths:
        rel = str(path.relative_to(ROOT))
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            name, default = None, None
            if isinstance(node, ast.Call):
                f = node.func
                if isinstance(f, ast.Attribute) and (
                    (f.attr == "getenv" and getattr(f.value, "id", None) == "os")
                    or (f.attr == "get" and getattr(f.value, "attr", None) == "environ")
                ):
                    if node.args and isinstance(node.args[0], ast.Constant):
                        name = node.args[0].value
                        if len(node.args) > 1:
                            value, ok = _literal(node.args[1])
                            default = _env_value(value) if ok else None
            elif isinstance(node, ast.Subscript) and getattr(node.value, "attr", None) == "environ":
                if isinstance(node.slice, ast.Constant):
                    name = node.slice.value
            if isinstance(name, str) and re.fullmatch(r"[A-Z][A-Z0-9_]+", name):
                if SECRET.search(name):
                    default = None
                found.setdefault(name, (rel, default))
    return found


def generated(head_names: set[str]) -> str:
    lines = [
        MARKER,
        "# Every other setting the code reads, with its default. A commented line is optional; a line",
        "# without # has no default and must be set. Run `uv run python scripts/env_example.py` after",
        "# changing a settings class; tests/unit/test_env_example.py fails while this part is stale.",
    ]
    seen = set(head_names)
    for rel, cls, fields in settings_fields():
        block = []
        for name, text, required, description in fields:
            if name in seen:
                continue
            seen.add(name)
            if description:
                block.append(f"# {description}")
            block.append(f"{name}=" if required else f"# {name}={text or ''}")
        if block:
            lines += ["", f"# {rel} ({cls})", *block]
    rest = [(n, src, d) for n, (src, d) in sorted(direct_reads().items()) if n not in seen]
    if rest:
        lines += ["", "# Read directly (os.getenv / os.environ)"]
        for name, src, default in rest:
            lines.append(f"# {name}={default or ''}   ({src})")
    return "\n".join(lines) + "\n"


def split_example() -> tuple[str, str]:
    text = EXAMPLE.read_text(encoding="utf-8")
    if MARKER not in text:
        return text.rstrip("\n") + "\n\n", ""
    head, tail = text.split(MARKER, 1)
    return head, MARKER + tail


def head_problems(head: str) -> list[str]:
    read = {name for _, _, fields in settings_fields() for name, *_ in fields} | set(direct_reads())
    problems = []
    for name in sorted(set(NAME_LINE.findall(head))):
        if name not in read and name not in EXTERNAL and not DYNAMIC.match(name):
            problems.append(f".env.example names {name}, which nothing reads: remove it")
    return problems


def main() -> int:
    head, tail = split_example()
    fresh = generated(set(NAME_LINE.findall(head)))
    if "--check" in sys.argv:
        problems = head_problems(head)
        if tail != fresh:
            problems.append(
                ".env.example's generated part is out of date: run `uv run python scripts/env_example.py`"
            )
        for problem in problems:
            print(problem)
        return 1 if problems else 0
    EXAMPLE.write_text(head + fresh, encoding="utf-8")
    print(f"wrote {EXAMPLE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
